projects/storefrontapp-e2e/src/page-objects/cmslib/header.po.ts
projects/storefrontapp-e2e/src/suites/language.e2e-spec.ts

E2E test for language switch.
Tests:
- URL does not change when switching language
- inputs in forms are not removed when changing lang
- language is changed with the switch
- refresh keeps language settings
Should close #61

E2E test for language switch

---

projects/storefrontlib/src/lib/cms-lib/search-box/search-box.component.spec.ts
projects/storefrontlib/src/lib/cms-lib/search-box/search-box.component.ts

GH-111: Add search query from state into search input field

---

projects/storefrontlib/src/lib/cms/components/dynamic-slot/component-wrapper.directive.spec.ts
projects/storefrontlib/src/lib/cms/components/dynamic-slot/component-wrapper.directive.ts
projects/storefrontlib/src/lib/cms/components/dynamic-slot/dynamic-slot.component.html
projects/storefrontlib/src/lib/product/components/product-details/container/product-details.component.html

Feature/GH-327 rename yComponentWrapper

---

projects/storefrontlib/src/lib/ui/layout/product-details-page-layout/product-details-page-layout.component.spec.ts

Removed leftover auth store

---

projects/storefrontlib/src/lib/cms-lib/link/link.component.html
projects/storefrontlib/src/lib/cms-lib/link/link.component.spec.ts
projects/storefrontlib/src/lib/cms-lib/link/link.component.ts

Feature/gh-393 Refactor link component

---

ci-scripts/lint.sh

GH-447: added html to prettier command

---

projects/storefrontlib/src/lib/cx-api/cx-api.service.spec.ts

GH-432: Added type safety to cx-api module

---

projects/storefrontapp/src/index.html

GH-374: feature(pwa): add metatags for apple devices

---

docs/contributorsetup.md
docs/setupandinstallation.md

Update the node.js version in the _contributorsetup.md_ and _setupandinstallation.md_ docs.

GH-554: Updated node version in installation docs

---

projects/core/src/occ/occ-models/cms-component.models.ts
projects/storefrontlib/src/lib/cms-lib/paragraph/paragraph.component.html
projects/storefrontlib/src/lib/cms-lib/paragraph/paragraph.component.spec.ts
projects/storefrontlib/src/lib/cms-lib/paragraph/paragraph.component.ts

feat(@spartacus/storefront): Refactor paragraph cms component to use CmsComponentData

---

projects/storefrontapp-e2e/src/smoke/app.e2e-spec.ts

Because of problems with backend configuration we are disabling most of the tests.

chore: Only run app tests

---

projects/storefrontlib/src/lib/cms-lib/banner/banner.component.ts

Fixed incorrect target for banner components

---

.travis.yml

Adding parameter to sun sonar scan on Travis build

---

projects/storefrontlib/src/lib/product/components/product-details/product-images/product-images.component.html
projects/storefrontlib/src/lib/product/components/product-details/product-images/product-images.component.spec.ts
projects/storefrontlib/src/lib/product/components/product-details/product-images/product-images.component.ts
projects/storefrontlib/src/lib/product/components/product-details/product-summary/product-summary.component.html

fix(@spartacus/storefront): provide product context to PDP.images outlet

---

package.json
yarn.lock

ci: update prettier version (#1149)

---

projects/storefrontlib/src/lib/cms-lib/search-box/search-box.component.scss

fix(@spartacus/storefront): Search input invisible in mobile view #1030

---

projects/core/src/user/facade/user.service.spec.ts
projects/core/src/user/store/selectors/user-orders.selectors.spec.ts
projects/core/src/user/store/selectors/user-orders.selectors.ts

feature/GH-1258: Change getOrdersLoaded selector

---

projects/storefrontapp/src/app/app.module.ts
projects/storefrontlib/src/lib/product/components/product-list/container/product-list.component.spec.ts
projects/storefrontlib/src/lib/product/components/product-list/product-grid-item/product-grid-item.component.html
projects/storefrontlib/src/lib/product/components/product-list/product-grid-item/product-grid-item.component.spec.ts
projects/storefrontlib/src/lib/product/components/product-list/product-list-item/product-list-item.component.html
projects/storefrontlib/src/lib/product/components/product-list/product-list-item/product-list-item.component.spec.ts
projects/storefrontlib/src/lib/product/components/product-list/product-list.module.ts

GH-664: Added strip html to product list and grid

---

docs/compatibilty.md

Tweaks and edits to _compatibility.md_ for the Feb 13th release of our libs.

GH-1318: Edits to text of compatibility.md

---

projects/core/src/cms/store/actions/page.action.ts
projects/core/src/cms/store/effects/page.effect.ts
projects/core/src/cms/store/reducers/index.ts
projects/core/src/cms/store/reducers/page-data.reducer.ts
projects/core/src/cms/store/reducers/page-index.reducer.ts

Remove add page data action

---

projects/storefrontlib/src/lib/occ/docs/cms-component-implementation.md

Did a complete review of the Customizing CMS Components doc: https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/projects/storefrontlib/src/lib/occ/docs/cms-component-implementation.md

GH-1255: review and edit of Customizing CMS Components doc

---

package.json
yarn.lock

Click the yellow lightbulb that will be on the left beside the line number

feat(@spartacus/storefrontlib): TypeScript 3.2 - implicit any suggestions and “infer from usage” fixes [need Ang7] #494

---

projects/storefrontlib/src/lib/ui/components/form-components/item-counter/item-counter.component.ts

fix(@spartacus/storefront): revert renderer2 for item-counter

---

projects/storefrontapp-e2e-cypress/cypress/integration/login-e2e-spec.ts

Removing comments and adding selectors

Login test cleanup

---

docs/contributing/type-safety-guidelines.md
projects/storefrontapp-e2e-cypress/cypress/integration/register.e2e-spec.ts

GH-1129: add e2e register test for cypress

---

projects/storefrontlib/src/lib/ui/pages/pages.module.ts

fix: removed unnecessary routes

---

projects/storefrontstyles/scss/layout/_index.scss
projects/storefrontstyles/scss/layout/page-templates/_search-results-list.scss

feat(@spartacus/storefront): add correct place for facets in search results page

---

projects/storefrontlib/src/lib/cart/cart-shared/cart-item-list/cart-item-list.component.spec.ts
projects/storefrontlib/src/lib/cart/cart-shared/cart-item/cart-item.component.html
projects/storefrontlib/src/lib/cart/cart-shared/cart-item/cart-item.component.spec.ts

feat(@spartacus/storefront): Add promotions component into cart components

---

projects/core/src/routing/configurable-routes/configurable-routes.service.spec.ts
projects/core/src/routing/configurable-routes/configurable-routes.service.ts

fix(@spartacus/core): Fix removing child routes from not configurabe routes

---

projects/core/.release-it.changelog.json
projects/core/.release-it.json
projects/storefrontlib/.release-it.changelog.json
projects/storefrontlib/.release-it.json
projects/storefrontstyles/.release-it.changelog.json
projects/storefrontstyles/.release-it.json

Set npm tag in release-it configs.

chore: Add npm tag to release-it config

---

projects/storefrontapp-e2e-cypress/cypress/integration/regression/reset-password/reset-password.e2e-spec.ts

GH-1296: Reset password e2e tests.

---

projects/core/src/cms/facade/cms.service.spec.ts
projects/core/src/cms/facade/cms.service.ts
projects/core/src/cms/store/selectors/page.selectors.spec.ts
projects/core/src/cms/store/selectors/page.selectors.ts
projects/storefrontlib/src/lib/cms/services/cms-mapping.service.spec.ts
projects/storefrontlib/src/lib/cms/services/cms-mapping.service.ts
projects/storefrontlib/src/lib/cms/services/cms-routes.service.spec.ts
projects/storefrontlib/src/lib/cms/services/cms-routes.service.ts

GH-1681 moved mapping logic to core, so it is not needed anymore in CmsMappingService
Closes GH-1688

feat: Update CmsMappingService after GH-1681

---

projects/storefrontapp-e2e/src/page-objects/checkout/order-confirmation.po.ts
projects/storefrontapp-e2e/src/page-objects/checkout/review-form.po.ts
projects/storefrontapp-e2e/src/smoke/big-happy-path.e2e-spec.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/container/multi-step-checkout.component.html
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/container/multi-step-checkout.component.spec.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/container/multi-step-checkout.component.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/delivery-mode/delivery-mode.component.html
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/delivery-mode/delivery-mode.component.scss
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/delivery-mode/delivery-mode.component.spec.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/delivery-mode/delivery-mode.component.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/review-submit/review-submit.component.html
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/review-submit/review-submit.component.spec.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/review-submit/review-submit.component.ts
projects/storefrontlib/src/lib/checkout/components/order-confirmation/order-confirmation.component.html
projects/storefrontlib/src/lib/checkout/components/order-confirmation/order-confirmation.component.ts
projects/storefrontlib/src/lib/my-account/order/order-details/order-details.component.html
projects/storefrontlib/src/lib/my-account/order/order-details/order-details.component.ts

Naming has been changed. Only UI labels has been omitted.
closes #923

feat(storefrontlib, test): shippingMethod naming changed to deliveryMode

---

projects/storefrontlib/src/lib/store-finder/components/store-finder-search/store-finder-search.component.html
projects/storefrontlib/src/lib/store-finder/components/store-finder-search/store-finder-search.component.scss

GH-1785: Style fix

---

.travis.yml

since backend is not public anymore
Fixes #1802

GH-1802 Removing automatic deployment to github pages

---

projects/storefrontlib/src/lib/checkout/config/checkout-config.ts
projects/storefrontlib/src/lib/checkout/config/default-checkout-config.ts
projects/storefrontlib/src/lib/storefront-config.ts

feat: Add checkout config

---

projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/delivery-mode/delivery-mode.module.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/payment-method/payment-method.module.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/review-submit/review-submit.module.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/shipping-address/shipping-address.module.ts
projects/storefrontlib/src/lib/ui/layout/config/default-layout-config.ts
projects/storefrontstyles/scss/layout/_index.scss
projects/storefrontstyles/scss/layout/page-templates/_multistep-checkout-page.scss

Cms mapping for checkout components

---

projects/storefrontlib/src/lib/utils/forms/form-utils.spec.ts
projects/storefrontlib/src/lib/utils/forms/form-utils.ts

feat: implement a form field validator

---

projects/storefrontapp-e2e-cypress/cypress/helpers/login.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/update-password.e2e-spec.ts

GH-1164: Update Password e2e tests.

---

projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-orchestrator/checkout-orchestrator.component.spec.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-orchestrator/checkout-orchestrator.component.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-orchestrator/checkout-orchestrator.module.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/multi-step-checkout.module.ts
projects/storefrontlib/src/lib/checkout/config/checkout-config.ts
projects/storefrontlib/src/lib/checkout/guards/checkout.guard.spec.ts
projects/storefrontlib/src/lib/checkout/guards/checkout.guard.ts
projects/storefrontlib/src/lib/checkout/guards/index.ts
projects/storefrontlib/src/lib/checkout/index.ts

Checkout orchestrator component + checkout guard

---

projects/storefrontlib/src/translations/en/product-list.en.ts

GH-1974: Change the structure of the product-list translations

---

projects/core/src/user/facade/user.service.spec.ts
projects/core/src/user/facade/user.service.ts
projects/core/src/user/occ/user.service.spec.ts
projects/core/src/user/occ/user.service.ts
projects/core/src/user/store/actions/user-register.action.spec.ts
projects/core/src/user/store/actions/user-register.action.ts
projects/core/src/user/store/effects/user-register.effect.spec.ts
projects/core/src/user/store/effects/user-register.effect.ts
projects/core/src/user/store/user-state.ts

feature/GH-1187: add facade for close user account

---

projects/core/src/checkout/facade/checkout.service.ts
projects/core/src/checkout/store/checkout-state.ts
projects/core/src/checkout/store/effects/checkout.effect.spec.ts
projects/core/src/checkout/store/effects/checkout.effect.ts
projects/core/src/checkout/store/reducers/checkout.reducer.ts
projects/core/src/checkout/store/reducers/index.ts
projects/core/src/checkout/store/selectors/address-verification.selectors.spec.ts
projects/core/src/checkout/store/selectors/address-verification.selectors.ts
projects/core/src/checkout/store/selectors/card-types.selectors.spec.ts
projects/core/src/checkout/store/selectors/card-types.selectors.ts
projects/core/src/checkout/store/selectors/checkout.selectors.spec.ts
projects/core/src/checkout/store/selectors/checkout.selectors.ts
projects/storefrontlib/src/lib/checkout/checkout-details.service.spec.ts
projects/storefrontlib/src/lib/checkout/checkout-details.service.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/multi-step-checkout.module.ts

feat: update store checkout/steps to use LoaderState

---

projects/core/src/checkout/store/effects/checkout.effect.spec.ts
projects/core/src/checkout/store/effects/checkout.effect.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/container/multi-step-checkout.component.html
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/container/multi-step-checkout.component.ts

GH-2021: Multistep checkout container refactor

---

projects/storefrontlib/src/cms-structure/page/config/default-header.config.ts
projects/storefrontstyles/scss/_sparta-theme.scss
projects/storefrontstyles/scss/app.scss
projects/storefrontstyles/scss/components/index.scss
projects/storefrontstyles/scss/components/layout/_header.scss
projects/storefrontstyles/scss/components/layout/_index.scss
projects/storefrontstyles/scss/header/_header.scss

Add missing HamburgerMenuComponent

---

CONTRIBUTING.md

Updates and improvements based on recommendations from GH-516.

GH-516: Improvements to text

---

projects/storefrontlib/src/lib/checkout/config/default-checkout-config.ts
projects/storefrontlib/src/lib/checkout/guards/shipping-address-set.guard.ts

feat: create step type enum in checkout config

---

projects/storefrontlib/src/lib/checkout/checkout-details.service.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-progress/checkout-progress-mobile-bottom/checkout-progress-mobile-bottom.component.html
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-progress/checkout-progress-mobile-bottom/checkout-progress-mobile-bottom.component.scss
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-progress/checkout-progress-mobile-bottom/checkout-progress-mobile-bottom.component.spec.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-progress/checkout-progress-mobile-bottom/checkout-progress-mobile-bottom.component.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-progress/checkout-progress-mobile-bottom/checkout-progress-mobile-bottom.module.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-progress/checkout-progress-mobile-top/checkout-progress-mobile-top.component.html
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-progress/checkout-progress-mobile-top/checkout-progress-mobile-top.component.scss
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-progress/checkout-progress-mobile-top/checkout-progress-mobile-top.component.spec.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-progress/checkout-progress-mobile-top/checkout-progress-mobile-top.component.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-progress/checkout-progress-mobile-top/checkout-progress-mobile-top.module.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/shipping-address/shipping-address.module.ts
projects/storefrontlib/src/translations/en/checkout-progress.en.ts

GH-2001: Add checkout progress steps component for mobile version

---

projects/core/src/i18n/config/default-i18n-config.ts
projects/storefrontlib/src/lib/my-account/update-email/update-email-form/update-email-form.component.html
projects/storefrontlib/src/lib/my-account/update-email/update-email-form/update-email-form.component.spec.ts
projects/storefrontlib/src/lib/my-account/update-email/update-email.module.ts
projects/storefrontlib/src/lib/my-account/update-password/components/update-password-form/update-password-form.component.html
projects/storefrontlib/src/lib/my-account/update-password/components/update-password-form/update-password-form.component.spec.ts
projects/storefrontlib/src/lib/my-account/update-password/update-password.module.ts
projects/storefrontlib/src/lib/my-account/update-profile/components/update-profile-form.component.html
projects/storefrontlib/src/lib/my-account/update-profile/components/update-profile-form.component.spec.ts
projects/storefrontlib/src/lib/my-account/update-profile/update-profile.module.ts
projects/storefrontlib/src/translations/en/common.en.ts
projects/storefrontlib/src/translations/en/user.en.ts

feat: Update new hardcoded text from HTML templates

---

projects/storefrontapp-e2e-cypress/cypress/integration/regression/my-account/close-account.e2e-spec.ts

GH-1189: E2E tests for close account

---

projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/container/multi-step-checkout.component.html
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/delivery-mode/delivery-mode.component.html
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/delivery-mode/delivery-mode.component.spec.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/delivery-mode/delivery-mode.component.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/payment-method/payment-form/payment-form.component.html
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/payment-method/payment-form/payment-form.component.spec.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/payment-method/payment-form/payment-form.component.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/payment-method/payment-method.component.html
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/payment-method/payment-method.component.spec.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/payment-method/payment-method.component.ts

Delivery mode and payment details modifications

---

projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-progress/checkout-progress-mobile-bottom/checkout-progress-mobile-bottom.component.scss
projects/storefrontstyles/scss/layout/page-templates/_multistep-checkout-page.scss

GH-2089: Mobile styling for checkout columns

---

projects/core/tsconfig.lib.json
projects/storefrontlib/tsconfig.lib.json
tsconfig.compodoc.json
tsconfig.json

Update tsconfig with "lib":"esnext"

---

projects/core/src/i18n/config/default-i18n-config.ts
projects/storefrontlib/src/lib/checkout/checkout-details.service.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/checkout-progress/checkout-progress-mobile-top/checkout-progress-mobile-top.component.html
projects/storefrontlib/src/lib/checkout/config/default-checkout-config.ts
projects/storefrontlib/src/lib/checkout/guards/delivery-mode-set.guard.spec.ts
projects/storefrontlib/src/lib/checkout/guards/delivery-mode-set.guard.ts
projects/storefrontlib/src/lib/checkout/guards/shipping-address-set.guard.ts
projects/storefrontlib/src/translations/en/checkout-progress.en.ts
projects/storefrontlib/src/translations/en/checkout.en.ts
projects/storefrontlib/src/translations/index.ts

feat: Check and (fix if necessary) translation in checkout components 

---

projects/core/src/cart/store/effects/cart.effect.ts
projects/core/src/checkout/store/effects/checkout.effect.ts

Quick fix to unblock pipelines.
Added reloading checkout details after cart merge.

fix: Load checkout details after cart merge

---

projects/core/src/cart/facade/cart.service.spec.ts
projects/core/src/cart/store/actions/cart.action.ts
projects/core/src/cart/store/effects/cart.effect.ts
projects/core/src/checkout/store/effects/checkout.effect.ts

Fix issue with checkout stability after cart are merged with the anonymous cart.

fix: Checkout error on cart merge

---

projects/storefrontlib/src/lib/ui/layout/config/default-layout-config.ts
projects/storefrontstyles/scss/layout/page-templates/_multistep-checkout-page.scss

GH-2157: Modify Multi Step Checkout Template

---

projects/core/src/auth/facade/auth.service.spec.ts
projects/core/src/auth/facade/auth.service.ts
projects/core/src/auth/store/effects/user-token.effect.ts
projects/core/src/cms/facade/cms.service.ts
projects/storefrontlib/src/cms-components/user/login/login.component.ts
projects/storefrontlib/src/cms-structure/page/page-layout/page-layout.component.html
projects/storefrontlib/src/cms-structure/page/page-layout/page-layout.component.ts
projects/storefrontlib/src/cms-structure/page/slot/page-slot.component.html
projects/storefrontlib/src/cms-structure/page/slot/page-slot.component.spec.ts
projects/storefrontlib/src/cms-structure/page/slot/page-slot.component.ts

Error in console when user is logged in

Fix change detection issue related to page layout component

---

projects/storefrontlib/src/lib/checkout/checkout.module.ts
projects/storefrontlib/src/lib/checkout/components/checkout-orchestrator/checkout-orchestrator.module.ts
projects/storefrontlib/src/lib/checkout/guards/checkout.guard.spec.ts
projects/storefrontlib/src/lib/checkout/guards/checkout.guard.ts
projects/storefrontlib/src/lib/checkout/guards/index.ts
projects/storefrontlib/src/lib/checkout/guards/order-confirmation-page.guard.spec.ts
projects/storefrontlib/src/lib/checkout/guards/order-confirmation-page.guard.ts
projects/storefrontlib/src/lib/ui/pages/order-confirmation-page/order-confirmation-page.module.ts

feat: Provide CheckoutGuard in root and remove it from providers in modules #2318

---

yarn.lock

fix: update yarn.lock (#2364)

---

projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/review-submit/review-submit.component.spec.ts
projects/storefrontlib/src/lib/checkout/components/multi-step-checkout/review-submit/review-submit.component.ts
projects/storefrontlib/src/lib/checkout/components/order-confirmation/order-confirmation.component.ts

fix for failing tests (GH-2376)

---

package.json
yarn.lock

GH-2014 Downgrading version of ng-bootstrap to fix dropdown bug

---

scripts/publish-builds.sh

GH-2378 snapshot repos have their own README

---

projects/storefrontlib/src/lib/checkout/guards/delivery-mode-set.guard.spec.ts
projects/storefrontlib/src/lib/checkout/guards/index.ts
projects/storefrontlib/src/lib/checkout/guards/payment-details-set.guard.spec.ts
projects/storefrontlib/src/lib/checkout/guards/payment-details-set.guard.ts
projects/storefrontlib/src/lib/checkout/guards/shipping-address-set.guard.spec.ts

feat: Create guard for payment details set

---

projects/storefrontlib/package.json

GH-2014 Locking ng-bootstrap version to fix dropdown bug

---

projects/storefrontlib/src/cms-components/myaccount/update-email/update-email-form/update-email-form.component.html
projects/storefrontlib/src/translations/en/user.en.ts

fix(@spartacus/storefrontlib): change the translation for updateEmailForm to the correct one (GH-2431)

---

scripts/changelog.ts

Now it should pick up all breaking changes notes from commit messages.

chore: List all breaking changes in changelog

---

projects/storefrontlib/src/cms-components/product/product-details/product-images/product-images.component.html
projects/storefrontlib/src/shared/components/media/media.component.spec.ts
projects/storefrontlib/src/shared/components/media/media.component.ts
projects/storefrontlib/src/shared/components/media/media.service.spec.ts
projects/storefrontlib/src/shared/components/media/media.service.ts
projects/storefrontstyles/scss/components/product/details/_product-images.scss

fix product thumbnail selection

---

projects/storefrontapp-e2e-cypress/cypress/helpers/product-search.ts

fix: product each e2e test

---

projects/storefrontlib/src/lib/checkout/components/checkout-orchestrator/checkout-orchestrator.module.ts
projects/storefrontlib/src/lib/checkout/components/checkout-progress/checkout-progress-mobile-bottom/checkout-progress-mobile-bottom.module.ts
projects/storefrontlib/src/lib/checkout/components/checkout-progress/checkout-progress-mobile-top/checkout-progress-mobile-top.module.ts
projects/storefrontlib/src/lib/checkout/components/checkout-progress/checkout-progress.module.ts
projects/storefrontlib/src/lib/checkout/components/delivery-mode/delivery-mode.module.ts
projects/storefrontlib/src/lib/checkout/components/payment-method/payment-method.module.ts
projects/storefrontlib/src/lib/checkout/components/place-order/place-order.module.ts
projects/storefrontlib/src/lib/checkout/components/review-submit/review-submit.module.ts
projects/storefrontlib/src/lib/checkout/components/shipping-address/shipping-address.component.ts
projects/storefrontlib/src/lib/checkout/components/shipping-address/shipping-address.module.ts

GH-2534: Fixes for checkout

---

projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-as-persistent-user.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/payment-methods.ts

Fix e2e test

---

projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-management.component.ts
tslint.json

fix: side effects warning in lib build script #2570

---

projects/storefrontapp/tslint.json
projects/storefrontlib/tslint.json

chore: Remove `y-` prefix from tslint rules

---

projects/core/src/global-message/facade/global-message.service.ts
projects/core/src/global-message/http-interceptors/http-error.interceptor.ts
projects/core/src/global-message/index.ts

feature/GH-2415: api review - global-message

---

projects/storefrontlib/src/lib/checkout/components/checkout-progress/checkout-progress-mobile-top/checkout-progress-mobile-top.component.html
projects/storefrontlib/src/lib/checkout/components/checkout-progress/checkout-progress.component.html

fix: Rename route to routeName in checkout progress components

---

projects/storefrontlib/src/lib/checkout/index.ts

fix: Export checkout guards

---

projects/core/src/checkout/services/cart-page-meta.resolver.ts
projects/core/src/checkout/services/checkout-page-meta.resolver.ts
projects/core/src/cms/page/content-page-meta.resolver.ts
projects/core/src/product/services/category-page-meta.resolver.ts
projects/core/src/product/services/product-page-meta.resolver.ts
projects/core/src/product/services/search-page-meta.resolver.ts

GH-2638: Fix TranslationService import paths

---

projects/storefrontlib/src/cms-components/misc/icon/icon.component.ts

GH-2472: Fix for svg

---

projects/storefrontlib/src/cms-components/navigation/search-box/search-box-component.service.spec.ts
projects/storefrontlib/src/cms-components/navigation/search-box/search-box-component.service.ts
projects/storefrontlib/src/cms-components/navigation/search-box/search-box.component.html
projects/storefrontlib/src/cms-components/navigation/search-box/search-box.component.spec.ts
projects/storefrontlib/src/cms-components/navigation/search-box/search-box.component.ts
projects/storefrontlib/src/cms-components/navigation/search-box/search-box.model.ts
projects/storefrontstyles/scss/components/product/search/_searchbox.scss

feat(searchbox): show products, product images and suggestions in the searchbox based on configuration

---

projects/core/src/product/services/category-page-meta.resolver.spec.ts
projects/core/src/product/services/category-page-meta.resolver.ts
projects/storefrontlib/src/cms-components/navigation/search-box/search-box.component.html
projects/storefrontlib/src/cms-components/navigation/search-box/search-box.component.ts

fix(storefront): only category and brand related facets should appear in the PLP breadcrumb

---

projects/storefrontapp-e2e-cypress/cypress.json
projects/storefrontapp/src/environments/environment.ci.ts

Switch CI back to dev17

---

docs/current_drafts/ssr.md

[GH-2622] Doc draft for SSR

---

projects/storefrontlib/src/shared/components/generic-link/generic-link.component.html

fix(storefront): show content of external footer links

---

projects/core/src/auth/store/actions/open-id-token.action.spec.ts
projects/core/src/auth/store/effects/open-id-token.effect.spec.ts
projects/core/src/auth/store/effects/open-id-token.effect.ts
projects/core/src/auth/store/effects/user-token.effect.ts
projects/core/src/user/store/effects/user-register.effect.spec.ts
projects/core/src/user/store/effects/user-register.effect.ts
projects/storefrontlib/src/cms-components/user/login-form/login-form.component.spec.ts
projects/storefrontlib/src/cms-components/user/login-form/login-form.component.ts

fix: trigger open id token retrieval after the user token

---

projects/storefrontstyles/scss/components/content/navigation/_navigation-ui.scss

fix overlapping page elements on the navigation flyout

---

projects/storefrontapp/src/app/app.module.ts

feat: kyma integration is off by default

---

projects/storefrontapp-e2e-cypress/cypress/integration/regression/my-account/consent-management.e2e-spec.ts
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-management.component.html
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-management.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-management.component.ts

Remove 'Done' from consent page #2788

---

projects/core/src/global-message/http-interceptors/handlers/bad-request.handler.ts
projects/storefrontstyles/scss/components/content/navigation/_navigation-ui.scss

Dropdown content is overlapped by global message #2922

---

projects/storefrontlib/src/cms-components/myaccount/address-book/address-book.module.ts

fix: Cannot access address book #2918

---

projects/storefrontapp-e2e-cypress/cypress.json
projects/storefrontapp/src/environments/environment.ci.ts

Dev 17 is currently not available. To unblock merging let's switch for dev 8.
Will go back to dev 17 after the server has been restored.

fix: Switch temporarly CI server for dev 8

---

projects/storefrontlib/src/cms-components/myaccount/address-book/address-book.module.ts
projects/storefrontlib/src/cms-components/product/product-details/product-summary/product-summary.component.html
projects/storefrontlib/src/cms-components/product/product-details/product-summary/product-summary.component.ts

fix: Button "Show reviews" on PDP disappeared #2929

---

projects/core/src/cart/facade/cart.service.spec.ts
projects/core/src/cart/facade/cart.service.ts

feature/GH-2937: when init cart, need to make sure the active baseSite is set

---

projects/storefrontlib/src/cms-structure/page/page-layout/page-layout.component.html
projects/storefrontlib/src/cms-structure/page/page-layout/page-layout.component.ts
projects/storefrontlib/src/cms-structure/page/slot/page-slot.component.html

Add context for slot, page layout and components cxOutlets

---

projects/storefrontstyles/scss/cxbase/blocks/pagination.scss

GH-2933: Add cursor pointer to the pagination links

---

projects/storefrontlib/src/cms-structure/pwa/components/add-to-home-screen-banner/add-to-home-screen-banner.component.html

GH-2956: Change translation

---

projects/core/src/global-message/config/default-global-message-config.ts

GH-3005: Adjust the default delay in seconds for global messages.

---

projects/storefrontapp-e2e-cypress/cypress/helpers/added-to-cart-modal.ts

Fix: Failing E2E: added to cart modal (GH-3017)

---

projects/core/src/personalization/http-interceptors/occ-personalization-id.interceptor.ts
projects/core/src/personalization/http-interceptors/occ-personalization-time.interceptor.ts

Fix occ personalization interceptors for SSR
Closes GH-2988

Occ-personalization breaks SSR

---

projects/core/src/state/reducers/storage-sync.reducer.spec.ts
projects/core/src/state/reducers/storage-sync.reducer.ts

Bug in SSR after NGRX 8 upgrade

---

projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts

Fix: Failing/Inconsistent E2E: smoke/checkout-flow (GH-3173)

---

projects/storefrontapp-e2e-cypress/cypress/integration/regression/my-account/close-account.e2e-spec.ts

fix: Fix close account e2e test

---

projects/storefrontlib/src/cms-components/myaccount/order/order-history/order-history.component.spec.ts

feature/GH-3185: clicking on order id' gets stuck pending

---

projects/storefrontapp-e2e-cypress/cypress/helpers/cart.ts

[GH-3176] Fixing cart test

---

projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts

Fix: Failing/Unstable E2E: Checkout flow (GH-3223)

---

projects/assets/src/translations/en/common.ts

GH-2971: Add the missing translation

---

projects/storefrontapp-e2e-cypress/cypress/helpers/site-context-selector.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/site-context/currency/currency-product-search.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/site-context/language/langauge-product-details-page.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/site-context/language/language-cart-page.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/site-context/language/language-checkout-page.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/site-context/language/language-my-account-pages.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/site-context/language/language-product-search-page.e2e-spec.ts

Fix: Failing/Unstable E2E: Currency Product Details (GH-3222)

---

projects/core/src/state/state.module.ts
projects/storefrontlib/src/recipes/b2c-storefront.module.ts
projects/storefrontlib/src/recipes/storefront.module.ts

feat: moved StoreModule's and EffectsModule's forRoot() from core lib to the storefront module

---

projects/storefrontstyles/scss/components/form-components/_star-rating.scss

fix(styles): Fix calculated gradient rating background for safari

---

projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-form/payment-form.component.ts
projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-method.component.ts

fix: billing address is sent to backend

---

projects/storefrontstyles/scss/components/checkout/cart/_cart-item.scss

GH-3060 Adjusting Remove link styling

---

projects/storefrontstyles/scss/components/content/tab-paragraph-container/_tab-paragraph-container.scss

GH-3050 removing text-indent and replacing with a padding-left approach

---

projects/core/src/cart/store/cart-store.module.ts

fix: Add something to cart, reload, lose cart (GH-2981)

---

projects/core/src/occ/adapters/checkout/occ-checkout-payment.adapter.ts
projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-form/payment-form.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-form/payment-form.component.ts
projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-method.component.html
projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-method.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-method.component.ts

fix: payment details step

---

projects/storefrontstyles/scss/components/checkout/cart/_added-to-cart-dialog.scss

fix: remove old --cx-g-colors #3398

---

projects/storefrontapp-e2e-cypress/cypress/helpers/site-context-selector.ts
projects/storefrontapp-e2e-cypress/cypress/integration/mobile/my-account/order-history-no-orders-flow-mobile.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/my-account/order-history-no-orders-flow.e2e-spec.ts

Closes GH-3220
including order-history-no-orders from GH-3525

fix: Failing/Unstable E2E: Language My Account Pages (GH-3220)

---

projects/core/src/occ/config/config-from-meta-tag-factory.ts

[hotfix] Configuration from meta-tag doesn't work for SSR

---

projects/core/src/i18n/translation-chunk.service.ts

[hotfix] Fatal error when the storefront is configured without I18N

---

projects/storefrontstyles/scss/components/product/list/_product-facet-navigation.scss

fix: add filters styling on mobile

---

projects/core/src/kyma/store/kyma-store.module.ts
projects/storefrontapp/src/app/app.module.ts

feat: remove kyma refresh token from localStorage

---

projects/storefrontlib/src/cms-components/checkout/components/shipping-address/shipping-address.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/shipping-address.component.ts
projects/storefrontlib/src/shared/components/carousel/carousel.component.ts

Fix: Default shipping address is always selected automatically (GH-3656)

---

projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-method.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-method.component.ts

Fix: Default Payment Method not selected automatically (GH-3607)

---

projects/storefrontlib/src/shared/components/carousel/carousel.component.spec.ts
projects/storefrontlib/src/shared/components/carousel/carousel.component.ts

Fix: PDP: Thumbnail carousel pagination is not reloaded when navigating from one product to another (GH-3553)

---

projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-form/payment-form.component.html
projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-form/payment-form.component.spec.ts
projects/storefrontstyles/scss/components/checkout/steps/payment/_payment-form.scss

improvement: change for card and cvv number inputs from text to number

---

projects/core/src/occ/config/occ-config.ts
projects/core/src/occ/occ-models/index.ts
projects/core/src/occ/occ-models/occ-endpoints.model.ts
projects/core/src/occ/services/occ-endpoints.service.spec.ts

Closes #3399 
Related PR #3645

feat: Typesafe endpoints

---

projects/core/src/kyma/store/kyma-store.module.ts
projects/storefrontapp/src/app/app.module.ts

fix: remove kyma refresh token from localStorage

---

projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-form/payment-form.module.ts

fix for missing OnlyNumberDirective import

---

projects/storefrontapp-e2e-cypress/cypress/support/commands.ts

GH-3703: Add cypress as the reference type

---

projects/storefrontapp-e2e-cypress/cypress/integration/regression/site-context/language/language-registration-page.e2e-spec.ts

Fix: Failing E2E: language-registration-page.e2e-spec.ts (GH-3699)

---

projects/storefrontapp-e2e-cypress/cypress/integration/regression/my-account/update-profile.e2e-spec.ts
projects/storefrontapp/src/environments/environment.ts

Fix: Failing E2E: Update Profile (GH-3697)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/product-search.ts

Fix: Failing E2E: mobile/product-search-store-flow-mobile.e2e-spec.ts (GH-3705)

---

projects/core/src/i18n/i18next/i18next-translation.service.spec.ts
projects/core/src/i18n/i18next/i18next-translation.service.ts

fix: don't load translations if not initialized

---

projects/storefrontapp-e2e-cypress/cypress/helpers/register.ts
projects/storefrontapp-e2e-cypress/cypress/integration/mobile/register-mobile.e2e-spec.ts

Fix: mobile/register-mobile.e2e-spec.ts (GH-3733)

---

projects/core/src/auth/guards/auth-redirect.service.spec.ts
projects/core/src/auth/guards/auth-redirect.service.ts
projects/storefrontapp/src/environments/environment.ts
projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.ts

user redirected to previously viewed account page after logging out (GH-2737)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/auth-forms.ts

Fix: Failing E2E: smoke/login.e2e-spec.ts (GH-3737)

---

projects/assets/src/translations/en/common.ts
projects/core/src/global-message/http-interceptors/handlers/internal-server-error.handler.ts
projects/core/src/global-message/http-interceptors/index.ts
projects/core/src/global-message/models/response-status.model.ts

feature/GH-3340: capture internal server error

---

projects/storefrontapp-e2e-cypress/cypress/helpers/auth-forms.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/my-account/update-email.e2e-spec.ts

Fix: Failing E2E: regression/update-email.e2e-spec.ts (GH-3746)

---

tsconfig.json

fix: added rootDir property for ivy

---

projects/storefrontapp-e2e-cypress/cypress/helpers/auth-forms.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts
projects/storefrontapp-e2e-cypress/cypress/integration/mobile/checkout-flow-mobile.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/smoke/checkout-flow.e2e-spec.ts

Fix: Refactor checkout-flow e2e tests (GH-3745)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/payment-methods.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/my-account/payment-methods.e2e-spec.ts

Unstable E2E: regression/my-account/payment-methods.e2e-spec.ts (GH-3754)

---

projects/core/src/util/serialization-utils.spec.ts
projects/core/src/util/serialization-utils.ts

fix: handle circular dependencies in error serializer

---

scripts/publish-builds.sh

[GH-3744] Adding snapshot builds for assets library

---

projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-forms.ts

GH-3402: Clear form fields before typing new input for certain form in e2e tests.

---

projects/storefrontapp-e2e-cypress/cypress/helpers/auth-forms.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/register.ts

Fix: Unstable E2E: regression/register.e2e-spec.ts (GH-3753)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/auth-forms.ts
projects/storefrontapp-e2e-cypress/cypress/integration/mobile/register-mobile.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/register.e2e-spec.ts

Failing E2E: regression/register & mobile/register (GH-3779)

---

projects/core/src/global-message/store/effects/global-message.effect.ts

fix: Fix for leaking data in store when global message is removed

---

projects/storefrontapp-e2e-cypress/cypress/helpers/cart.ts

Unstable E2E: mobile/cart-mobile.e2e-spec.ts (GH-3752)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/auth-forms.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/my-account/payment-methods.e2e-spec.ts

Fix: Unstable E2E: regression/my-account/payment-methods.e2e-spec.ts (GH-3809)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/auth-forms.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/language.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/order-history.ts

Unstable E2E: regression/my-account/order-history-orders-flow.e2e-spec.ts (GH-3807)

---

projects/core/src/auth/guards/auth-redirect.service.spec.ts
projects/core/src/auth/guards/auth-redirect.service.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/my-account/update-email.e2e-spec.ts
projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.ts

Revert "user redirected to previously viewed account page after logging out (GH-2737)"

---

projects/core/src/occ/adapters/site-context/default-occ-site-context-config.ts
projects/core/src/occ/adapters/site-context/occ-site.adapter.spec.ts
projects/core/src/occ/adapters/site-context/occ-site.adapter.ts
projects/core/src/occ/adapters/site-context/site-context-occ.module.ts
projects/core/src/occ/occ-models/occ-endpoints.model.ts

feat: configurable occ endpoints for site context (#1795)

---

projects/core/src/occ/adapters/store-finder/default-occ-store-finder-config.ts
projects/core/src/occ/adapters/store-finder/occ-store-finder.adapter.spec.ts
projects/core/src/occ/adapters/store-finder/occ-store-finder.adapter.ts
projects/core/src/occ/adapters/store-finder/store-finder-occ.module.ts
projects/core/src/occ/occ-models/occ-endpoints.model.ts

feat: configurable occ endpoints for store finder

---

projects/storefrontlib/src/shared/components/star-rating/star-rating.component.ts

Hot-fix for #3541

---

projects/core/src/occ/adapters/cart/cart-occ.module.ts
projects/core/src/occ/adapters/cart/default-occ-cart-config.ts
projects/core/src/occ/adapters/cart/occ-cart-entry.adapter.spec.ts
projects/core/src/occ/adapters/cart/occ-cart-entry.adapter.ts
projects/core/src/occ/adapters/cart/occ-cart.adapter.spec.ts
projects/core/src/occ/adapters/cart/occ-cart.adapter.ts
projects/core/src/occ/occ-models/occ-endpoints.model.ts

feat: configurable endpoints for cart

---

projects/storefrontlib/src/cms-components/checkout/components/delivery-mode/delivery-mode.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/delivery-mode/delivery-mode.component.ts

fix for selected delivery fail on languages change

---

projects/storefrontlib/src/cms-components/checkout/config/checkout-config.ts
projects/storefrontlib/src/cms-components/checkout/config/default-checkout-config.ts

Add Express checkout config

---

projects/storefrontlib/src/cms-components/checkout/config/checkout-config.ts
projects/storefrontlib/src/cms-components/checkout/config/default-checkout-config.ts

Update Checkout configuration with default delivery mode

---

projects/core/src/occ/services/occ-endpoints.service.ts

fix: auth working when it doesn't start with a slash

---

projects/storefrontapp/src/environments/environment.ts
projects/storefrontlib/src/cms-components/checkout/components/checkout-progress/checkout-progress-mobile-bottom/checkout-progress-mobile-bottom.module.ts
projects/storefrontlib/src/cms-components/checkout/components/checkout-progress/checkout-progress-mobile-top/checkout-progress-mobile-top.module.ts
projects/storefrontlib/src/cms-components/checkout/components/checkout-progress/checkout-progress.module.ts
projects/storefrontlib/src/cms-components/checkout/components/delivery-mode/delivery-mode.module.ts
projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-method.module.ts
projects/storefrontlib/src/cms-components/checkout/components/place-order/place-order.module.ts
projects/storefrontlib/src/cms-components/checkout/components/review-submit/review-submit.module.ts
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/shipping-address.module.ts
projects/storefrontlib/src/cms-components/checkout/guards/checkout-auth.guard.spec.ts
projects/storefrontlib/src/cms-components/checkout/guards/checkout-auth.guard.ts
projects/storefrontlib/src/cms-components/user/checkout-login/checkout-login.component.spec.ts
projects/storefrontlib/src/cms-components/user/checkout-login/checkout-login.component.ts

feat: update checkout auth guard to go to checkout once 

---

projects/assets/src/translations/en/common.ts

wording fixed

---

projects/storefrontstyles/scss/components/store-finder/_store-finder-list-item.scss

Fix padding and alignment in storefinder map list

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-list-item/store-finder-list-item.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store-description/store-finder-store-description.component.html

Fix: show store address line 2

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store-description/store-finder-store-description.component.html

Fix: hide contact link on store details view

---

projects/storefrontstyles/scss/components/content/banner/_banner.scss

Fix for banner images width

---

projects/storefrontlib/src/cms-structure/page/component/component-wrapper.directive.spec.ts
projects/storefrontlib/src/cms-structure/page/component/component-wrapper.directive.ts

Fix cxApi.cmsComponentData naming

---

projects/storefrontlib/src/cms-structure/page/component/component-mapper.service.spec.ts
projects/storefrontlib/src/cms-structure/page/component/component-mapper.service.ts

Allows for declaring cms mapping without JS file specified (imported separately)
Closes GH-4056

Support for preloaded cms web components

---

projects/storefrontlib/src/cms-components/checkout/components/delivery-mode/delivery-mode.component.ts

fix: fix for shipping methods

---

projects/core/src/state/reducers/storage-sync.reducer.spec.ts
projects/core/src/state/reducers/storage-sync.reducer.ts

This reverts commit 64ce4ff426196eeb8540e8159925b09f6c3f0591.

Revert "fix: Storage Sync Does Not Sync ( right away ) (#4052)"

---

projects/storefrontlib/src/cms-structure/page/component/component-mapper.service.spec.ts
projects/storefrontlib/src/cms-structure/page/component/component-mapper.service.ts

This reverts commit 4cda41618ceddca3c5282cb4a6bcf62bd706429b.

Revert "Support for preloaded cms web components (#4057)"

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-list-item/store-finder-list-item.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-list-item/store-finder-list-item.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-map/store-finder-map.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-list/store-finder-list.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-list/store-finder-list.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-list/store-finder-list.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-search-result.component.html
projects/storefrontstyles/scss/components/store-finder/_store-finder-list-item.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-list.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-map.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-search-result.scss

Fix: storefinder pagination and scrolling fixes

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store-description/store-finder-store-description.component.html

fix: hide call link in store details if no phone number provided

---

projects/core/src/cms/store/cms-store.module.ts
projects/core/src/product/store/product-store.module.ts
projects/core/src/site-context/store/site-context-store.module.ts
projects/core/src/state/reducers/storage-sync.reducer.spec.ts
projects/core/src/state/reducers/storage-sync.reducer.ts
projects/core/src/state/reducers/transfer-state.reducer.spec.ts
projects/core/src/state/reducers/transfer-state.reducer.ts
projects/core/src/state/utils/get-state-slice.spec.ts
projects/core/src/state/utils/get-state-slice.ts

fix: filter config keys for ssr that have a falsy value

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search/store-finder-search.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search/store-finder-search.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search/store-finder-search.component.ts
projects/storefrontstyles/scss/components/store-finder/_store-finder-search.scss

Update storefront search UI

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-list-item/store-finder-list-item.component.html
projects/storefrontstyles/scss/components/store-finder/_store-finder-grid.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-list-item.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-search-result.scss

Pagination and View all stores improvements

---

.gitignore
.vscode/README.md
.vscode/extensions.json
.vscode/recommended-settings.json

feat: add recommended vscode extensions and settings

---

projects/core/src/occ/adapters/cart/default-occ-cart-config.ts
projects/core/src/occ/adapters/cart/occ-cart.adapter.spec.ts
projects/core/src/occ/adapters/cart/occ-cart.adapter.ts
projects/core/src/occ/occ-models/occ-endpoints.model.ts

feature/GH-3930: Make occ call to add email to the cart configurable

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search/store-finder-search.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search/store-finder-search.component.spec.ts

fix to open store details in View All Stores section

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search/store-finder-search.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store-description/store-finder-store-description.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-stores-count/store-finder-stores-count.component.html
projects/storefrontstyles/scss/components/store-finder/_store-finder-list-item.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-list.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-map.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-search-result.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-store-description.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-stores-count.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder.scss

Fix: layout clean up on store details page and store finder list styles adjustments

---

projects/core/src/cart/store/effects/cart.effect.ts
projects/core/src/cart/store/selectors/cart.selector.ts
projects/core/src/config/utils/dynamic-template.ts

Cart breaks gracefully

---

projects/core/src/cms/store/effects/page.effect.ts

Fix refresh page logic

---

projects/storefrontstyles/scss/components/store-finder/_store-finder-list.scss

Fix: change background color for focused store on list

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-list/store-finder-list.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-list/store-finder-list.component.ts
projects/storefrontstyles/scss/components/store-finder/_store-finder-list.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-search.scss

Fix to center map for selected store on mobile

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-list/store-finder-list.component.ts

Fix: Scroll to Top method not working properly

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-list-item/store-finder-list-item.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store-description/store-finder-store-description.component.html
projects/storefrontstyles/scss/components/store-finder/_store-finder-list.scss

Fix: Remove trailing commas from store descriptions

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store-description/store-finder-store-description.component.ts

Fix: change urls in store finder to be more user friendly

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store-description/store-finder-store-description.component.spec.ts

Fix: Unit tests fail on wrong url parsing for store details

---

projects/core/src/state/config/default-state-config.ts
projects/core/src/state/config/state-config.ts
projects/core/src/state/reducers/storage-sync.reducer.spec.ts
projects/core/src/state/reducers/storage-sync.reducer.ts
projects/core/src/state/reducers/transfer-state.reducer.ts
projects/core/src/state/utils/get-state-slice.spec.ts
projects/core/src/state/utils/get-state-slice.ts

feat: Introduce excludeKeys once again (after revert #3998) #4036

---

projects/core/src/site-context/services/site-context-url-serializer.spec.ts
projects/core/src/site-context/services/site-context-url-serializer.ts

when you go to url like /contextParam1/contextParam2/?any=thing - it redirects to /contextParam1/contextParam2/contextParam2?any=thing
Closes GH-4149

Fix: site context / routing issue

---

projects/storefrontlib/src/cms-components/storefinder/components/abstract-store-item/abstract-store-item.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-list-item/store-finder-list-item.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store-description/store-finder-store-description.component.html

Fix: remove unnecessary space before commas in stores address

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-list/store-finder-list.component.html
projects/storefrontstyles/scss/components/store-finder/_store-finder-list.scss

fix: adjust go back button with storefinder styling

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store-description/store-finder-store-description.component.html
projects/storefrontstyles/scss/components/store-finder/_store-finder-store-description.scss

GH-4175: Fix for store details width on tablet

---

projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.ts
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/shipping-address.component.html
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/shipping-address.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/shipping-address.component.ts
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/shipping-address.module.ts
projects/storefrontlib/src/cms-components/checkout/guards/checkout-details-loaded.guard.spec.ts
projects/storefrontlib/src/cms-components/checkout/guards/checkout-details-loaded.guard.ts
projects/storefrontlib/src/cms-components/checkout/guards/index.ts
projects/storefrontlib/src/cms-components/checkout/services/checkout-details.service.spec.ts
projects/storefrontlib/src/cms-components/checkout/services/checkout-details.service.ts

feature/GH-4152: Guest checkout shipping address population

---

projects/core/src/occ/adapters/store-finder/default-occ-store-finder-config.ts
projects/core/src/occ/adapters/store-finder/occ-store-finder.adapter.spec.ts
projects/core/src/occ/adapters/store-finder/occ-store-finder.adapter.ts
projects/core/src/store-finder/facade/store-finder.service.spec.ts
projects/core/src/store-finder/facade/store-finder.service.ts
projects/core/src/store-finder/store/actions/find-stores.action.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-list-item/store-finder-list-item.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-list-item/store-finder-list-item.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-list/store-finder-list.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-list/store-finder-list.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-search-result.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-search-result.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-search-result.component.ts
projects/storefrontstyles/scss/components/store-finder/_store-finder-list-item.scss

GH-4238: Add useMyLocation functionality

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-list-item/store-finder-list-item.component.html

fix: cancel event propagation for button get direction on view all stores

---

projects/storefrontlib/src/cms-components/storefinder/components/index.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-list-item/store-finder-list-item.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store-description/store-finder-store-description.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store-description/store-finder-store-description.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store-description/store-finder-store-description.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store/store-finder-store.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store/store-finder-store.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store/store-finder-store.component.ts
projects/storefrontlib/src/cms-components/storefinder/store-finder.module.ts
projects/storefrontstyles/scss/_sparta-theme.scss
projects/storefrontstyles/scss/components/store-finder/_index.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-store.scss

fix: add go back button for store finder store details view

---

projects/schematics/src/add-spartacus/index.ts
projects/schematics/src/utils/ast-utils.ts

Fixes 'Cannot read property 'kind' of undefined' exception in schematics
Closes GH-4264

fix: schematics exception

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.ts
projects/storefrontstyles/scss/components/store-finder/_store-finder-grid.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-list.scss

Add pagination for view all stores

---

projects/core/src/occ/adapters/cart/occ-cart-entry.adapter.spec.ts
projects/core/src/occ/adapters/cart/occ-cart-entry.adapter.ts
projects/core/src/occ/adapters/cart/occ-cart.adapter.spec.ts
projects/core/src/occ/adapters/cart/occ-cart.adapter.ts
projects/core/src/occ/adapters/user/occ-user-order.adapter.spec.ts
projects/core/src/occ/adapters/user/occ-user-order.adapter.ts
projects/storefrontlib/src/feature-toggles.ts

Remove explicit feature flag for configurable occ endpoints

---

projects/core/src/checkout/facade/checkout-delivery.service.ts
projects/core/src/checkout/facade/checkout-payment.service.ts
projects/core/src/checkout/store/actions/checkout.action.ts
projects/core/src/checkout/store/checkout-state.ts
projects/core/src/checkout/store/effects/checkout.effect.ts
projects/storefrontlib/src/cms-components/checkout/services/checkout-config.service.spec.ts
projects/storefrontlib/src/cms-components/checkout/services/checkout-config.service.ts
projects/storefrontlib/src/cms-components/checkout/services/express-checkout.service.spec.ts
projects/storefrontlib/src/cms-components/checkout/services/express-checkout.service.ts

feat: unit tests for express checkout #4054

---

projects/storefrontapp/src/app/app.module.ts
projects/storefrontlib/src/recipes/storefront-foundation.module.ts

Set default feature level to 1.0

---

projects/schematics/package.json
projects/schematics/yarn.lock

Update schematics dependencies

---

projects/core/.release-it.json
projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts

Cherry-pick fix for e2e tests from develop and fix prettier error.

Fix checkout-flow.e2e-spec.ts (GH-4282)

---

projects/storefrontlib/src/cms-components/content/index.ts

feat: Export banner carousel in index (#4275)

---

projects/assets/src/translations/en/store-finder.ts
projects/core/src/store-finder/facade/store-finder.service.spec.ts
projects/core/src/store-finder/facade/store-finder.service.ts

fix: handle error message for disabled geolocation

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.ts
projects/storefrontstyles/scss/components/store-finder/_store-finder-grid.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-list.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-search-result.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder.scss

 Revert: Add pagination for view all stores #4232

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search/store-finder-search.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search/store-finder-search.component.ts
projects/storefrontstyles/scss/components/store-finder/_store-finder-search.scss

fix: do not display reaults when search value not provided

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store/store-finder-store.component.ts

revert: store url readable format parse

---

projects/storefrontlib/src/cms-components/checkout/guards/checkout.guard.spec.ts
projects/storefrontlib/src/cms-components/checkout/guards/checkout.guard.ts
projects/storefrontlib/src/cms-components/myaccount/address-book/address-book.component.service.spec.ts
projects/storefrontlib/src/cms-components/myaccount/address-book/address-book.component.service.ts
projects/storefrontlib/src/cms-components/myaccount/address-book/address-card/address-card.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/address-book/address-card/address-card.component.ts

Ensure to keep correct feature versioning in EC-FR1 #4140

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/payment-details.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

feat: Tabbing Order E2E Tests - Payment Details (#4216)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/personal-details.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

feat: add personal details tests

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-list/store-finder-list.component.ts

fix: change action scroll behaviour for selected pin #4409

---

projects/storefrontlib/src/cms-components/storefinder/components/abstract-store-item/abstract-store-item.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/abstract-store-item/abstract-store-item.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-grid/store-finder-grid.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-header/store-finder-header.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-list-item/store-finder-list-item.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-pagination-details/store-finder-pagination-details.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search/store-finder-search.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search/store-finder-search.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store-description/store-finder-store-description.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store/store-finder-store.component.spec.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-stores-count/store-finder-stores-count.component.spec.ts

refactor storefinder unit tests #4371

---

projects/storefrontapp-e2e-cypress/cypress/integration/regression/store-finder.e2e-spec.ts

adjust storefinder e2e tests #1409

---

projects/core/src/store-finder/store/effects/view-all-stores.effect.ts

fix: display view all country list in alphabetical order

---

projects/core/src/auth/store/effects/user-token.effect.ts

GH-4385: Handle Customer Emulation Token Expiry

---

projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-list/store-finder-list.component.ts
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-store/store-finder-store.component.html
projects/storefrontlib/src/cms-components/storefinder/components/store-finder-stores-count/store-finder-stores-count.component.html
projects/storefrontstyles/scss/components/store-finder/_store-finder-list-item.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-list.scss
projects/storefrontstyles/scss/components/store-finder/_store-finder-store.scss

fix: minor visual issues and improvements

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/consent-management.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

feat: Tabbing Order E2E Tests - Consent Management (#4220)

---

projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.html

feat: fix footer links tabbing order

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/add-to-cart.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

feat: Tabbing Order E2E Tests - Add To Cart (#4202)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/login.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/auth-forms.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

feat: add second test for login page

---

projects/storefrontlib/src/cms-components/order-confirmation/components/guest-register-form/guest-register-form.component.html
projects/storefrontlib/src/cms-components/order-confirmation/components/guest-register-form/guest-register-form.component.ts
projects/storefrontlib/src/cms-components/order-confirmation/components/order-confirmation-thank-you-message/order-confirmation-thank-you-message.component.html
projects/storefrontlib/src/cms-components/order-confirmation/components/order-confirmation-thank-you-message/order-confirmation-thank-you-message.component.spec.ts
projects/storefrontstyles/scss/_sparta-theme.scss
projects/storefrontstyles/scss/components/checkout/order-confirmation/_guest-register-form.scss
projects/storefrontstyles/scss/components/checkout/order-confirmation/_index.scss

Styling for guest register form (#4449)

---

projects/storefrontapp/src/app/app.module.ts
projects/storefrontlib/src/cms-components/checkout/guards/checkout-auth.guard.spec.ts
projects/storefrontlib/src/cms-components/checkout/guards/checkout-auth.guard.ts
projects/storefrontlib/src/cms-components/user/login-form/login-form.component.spec.ts
projects/storefrontlib/src/cms-components/user/login-form/login-form.component.ts
projects/storefrontlib/src/feature-toggles.ts

feature/GH-3891: Feature flag to enable/disable guest checkout

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/cart.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

feat: Tabbing Order E2E Tests - Cart (#4203)

---

projects/storefrontlib/src/cms-components/user/checkout-login/checkout-login.module.ts

fix: login can redirect to guest login page (#4461)

---

projects/assets/src/translations/en/my-account.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/product-search.ts
projects/storefrontlib/src/cms-components/myaccount/close-account/components/close-account-modal/close-account-modal.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/close-account/components/close-account-modal/close-account-modal.component.ts
projects/storefrontlib/src/shared/components/card/card.component.spec.ts

fix: Close Account: Confirmation dialog does not close upon an error (GH-3773)

---

projects/storefrontlib/src/cms-structure/routing/suffix-routes/suffix-url-matcher.ts

doc: fix comment for suffix url matcher

---

projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts
projects/storefrontlib/src/cms-components/user/login-form/login-form.component.html
projects/storefrontlib/src/cms-components/user/login-form/login-form.component.spec.ts
projects/storefrontlib/src/cms-components/user/login-form/login-form.component.ts

feat: Login Button should not be disabled (#4483)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/checkout/shipping-address.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/login.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-forms.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

feat: add shipping address tests

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/checkout/shipping-address.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

feat: add existing shipping address tests

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/address-book.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

feat: Tabbing Order E2E Tests - Address Book (Add Address) (#4214)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/checkout/delivery-mode.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

feat: add delivery mode tests

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts

fix: Fix tabbing e2e tests asseting wrong occ data

---

projects/core/src/cart/connectors/cart/cart-connector.spec.ts
projects/core/src/cart/connectors/cart/cart.adapter.ts
projects/core/src/cart/connectors/cart/cart.connector.ts
projects/core/src/cart/facade/cart.service.spec.ts
projects/core/src/cart/facade/cart.service.ts
projects/core/src/cart/store/actions/cart.action.spec.ts
projects/core/src/cart/store/actions/cart.action.ts
projects/core/src/cart/store/effects/cart.effect.spec.ts
projects/core/src/cart/store/effects/cart.effect.ts
projects/core/src/checkout/store/effects/checkout.effect.spec.ts
projects/core/src/checkout/store/effects/checkout.effect.ts
projects/core/src/occ/adapters/cart/default-occ-cart-config.ts
projects/core/src/occ/adapters/cart/occ-cart.adapter.spec.ts
projects/core/src/occ/adapters/cart/occ-cart.adapter.ts
projects/core/src/occ/occ-models/occ-endpoints.model.ts
projects/storefrontlib/src/cms-components/checkout/services/checkout-details.service.ts

Guest cart merge with user cart

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/order-history.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

feat: Tabbing Order E2E Tests - Order History

---

projects/core/src/occ/adapters/cart/default-occ-cart-config.ts
projects/core/src/occ/adapters/cart/occ-cart.adapter.spec.ts
projects/core/src/occ/adapters/cart/occ-cart.adapter.ts

GH-4539: Remove email from url

---

projects/storefrontlib/src/components/asm/asm-root/asm-root.component.spec.ts
projects/storefrontlib/src/layout/main/main.module.ts
projects/storefrontlib/src/layout/main/storefront.component.html
projects/storefrontlib/src/layout/main/storefront.component.spec.ts
projects/storefrontlib/src/shared/test/mock-feature-level-directive.ts

GH-4528: When asm feature is off, remove cx-asm tag from dom.

---

projects/storefrontapp-e2e-cypress/cypress.json
projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts
projects/storefrontapp-e2e-cypress/cypress/integration/smoke/asm.e2e-spec.ts
projects/storefrontapp/src/environments/environment.ci.ts

GH-4515: Add first asm e2e tests.

---

projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.html
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.ts

feat: Add Address Button should not be disabled 

---

projects/assets/src/translations/en/user.ts
projects/storefrontlib/src/cms-components/order-confirmation/components/order-confirmation-thank-you-message/order-confirmation-thank-you-message.component.html
projects/storefrontlib/src/cms-components/user/checkout-login/checkout-login.component.html
projects/storefrontlib/src/cms-components/user/checkout-login/checkout-login.component.spec.ts
projects/storefrontlib/src/cms-components/user/checkout-login/checkout-login.component.ts

GH-4555: Fix form validation

---

projects/core/src/checkout/store/effects/checkout.effect.ts
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.ts
projects/storefrontlib/src/cms-components/checkout/services/checkout-details.service.ts
projects/storefrontlib/src/cms-components/order-confirmation/components/order-confirmation-thank-you-message/order-confirmation-thank-you-message.component.html

fix: Fix regions error in checkout

---

.github/api-extractor-action/index.js

chore: Improve bot with warning about core lib

---

.github/api-extractor-action/index.js
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/shipping-address.component.ts

fix: Change diff in breaking change bot report

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/review-order.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

feat: Tabbing Order E2E Tests - Review Order

---

projects/storefrontlib/src/cms-components/checkout/guards/index.ts
projects/storefrontlib/src/cms-components/checkout/guards/not-checkout-auth.guard.spec.ts
projects/storefrontlib/src/cms-components/checkout/guards/not-checkout-auth.guard.ts
projects/storefrontlib/src/cms-components/user/checkout-login/checkout-login.module.ts

feature/GH-4548: add NotCheckoutAuthGuard

---

projects/storefrontlib/src/cms-components/order-confirmation/components/order-confirmation-overview/order-confirmation-overview.component.ts

GH-3735: Fix order confirmation bug

---

projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.html
projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.ts
projects/storefrontstyles/scss/components/content/navigation/_navigation-ui.scss

feat: Header Category Tab Key Navigation

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/checkout/delivery-mode.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/checkout/payment-details.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/checkout/review-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/checkout/shipping-address.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts
projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item/cart-item.component.html

feat: add review order tests

---

projects/storefrontlib/src/cms-components/user/login/login.component.html
projects/storefrontlib/src/cms-components/user/login/login.component.spec.ts
projects/storefrontlib/src/cms-components/user/login/login.component.ts

feature/GH-4694: bring back login/register link

---

.vscode/README.md
.vscode/launch.json

feat: add debug support for firefox to vscode

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/header.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

feat: Tabbing Order E2E Tests - Header Desktop

---

README.md

docs: Fix Slack invite link in readme (GH-4711)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/express-checkout.e2e-spec.ts

fix: express-checkout.e2e-spec.ts failing #4668

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/checkout/delivery-mode.ts
projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.spec.ts

fix unit tests

---

projects/core/src/auth/http-interceptors/auth-error.interceptor.ts
projects/core/src/user/facade/user-address.service.ts
projects/core/src/user/facade/user-consent.service.ts
projects/core/src/user/facade/user-payment.service.ts
projects/core/src/user/facade/user.service.ts

GH-4075: Set the proper deprecated since version for deprecated code.

---

projects/storefrontapp-e2e-cypress/cypress.json
projects/storefrontapp/src/environments/environment.ci.ts

GH-4526: Revert e2e tests temporary configs.

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/header.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

feat: Tabbing Order E2E Tests - Header Mobile

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/header.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/product-list.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts
projects/storefrontlib/src/cms-components/product/product-list/product-grid-item/product-grid-item.component.html
projects/storefrontlib/src/cms-components/product/product-list/product-list-item/product-list-item.component.html
projects/storefrontlib/src/cms-components/product/product-list/product-view/product-view.component.html
projects/storefrontlib/src/shared/components/list-navigation/pagination/pagination.component.html

feat: Tabbing Order E2E Tests - Product List 

---

projects/storefrontlib/src/components/asm/asm-main-ui/asm-main-ui.component.html
projects/storefrontlib/src/components/asm/asm-main-ui/asm-main-ui.component.spec.ts
projects/storefrontlib/src/components/asm/csagent-login-form/csagent-login-form.component.html
projects/storefrontlib/src/components/asm/csagent-login-form/csagent-login-form.component.spec.ts
projects/storefrontlib/src/components/asm/csagent-login-form/csagent-login-form.component.ts

GH-4530: Fix bug

---

projects/schematics/README.md
projects/schematics/src/add-spartacus/index.ts

fix: supply missing infite-scroll dependency #4772

---

projects/assets/src/translations/en/product.ts
projects/assets/src/translations/translation-chunks-config.ts
projects/storefrontlib/src/cms-components/product/product-list/product-list.module.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.html
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.spec.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.module.ts
projects/storefrontlib/src/recipes/config/b2c-layout-config.ts
projects/storefrontstyles/scss/layout/_index.scss
projects/storefrontstyles/scss/layout/page-templates/_search-results-grid.scss

Fix: broken search results page

---

projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-form/payment-form.component.ts

fix: payment form address object null check (#4194)

---

projects/core/src/checkout/store/effects/checkout.effect.ts

fix: "Cart Not Found" error when choosing a default address #4722

---

projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-form/payment-form.component.ts

fix: payment form address object null check

---

projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts
projects/storefrontapp-e2e-cypress/cypress/integration/mobile/checkout-flow-mobile.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/billing-address.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/checkout-as-guest.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/express-checkout.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/smoke/checkout-flow.e2e-spec.ts
projects/storefrontlib/src/cms-components/checkout/components/delivery-mode/delivery-mode.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/delivery-mode/delivery-mode.component.ts

pre-select preferred delivery mode always if not chosen any before
Closes #4468

feat: Select shipping cost automatically like express checkout does #4468

---

projects/assets/src/translations/en/asm.ts
projects/core/public_api.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/asm.ts
projects/storefrontlib/src/cms-components/asm/asm-root/asm-root.component.ts
projects/storefrontlib/src/cms-components/asm/customer-selection/customer-selection.component.ts
projects/storefrontlib/src/cms-components/index.ts

GH-4806: Remove asm from the public libraries and align labels.

---

projects/core/src/product/services/search-page-meta.resolver.ts

Counterpart to #4752 for release branch.

fix: remove filter that was causing breadcrumbs to be left behind (GH-3572)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/asm.ts

closes GH-4812
The actual fix is on line 82.

GH-4812: Fix delivery mode issue and update test titles.

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/header.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts
projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.ts

fix: Fix My Account being unreachable via tab key 

---

projects/assets/src/translations/en/product.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.html
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.ts
projects/storefrontstyles/scss/components/product/details/_product-variant-selector.scss

fix: display selected style option

---

projects/storefrontlib/src/cms-components/asm/customer-selection/customer-selection.component.spec.ts
projects/storefrontlib/src/cms-components/asm/customer-selection/customer-selection.component.ts

GH-4830: Allow case insenitive customer match.

---

projects/storefrontlib/src/cms-structure/services/cms-guards.service.ts
projects/storefrontlib/src/cms-structure/services/cms-i18n.service.ts
projects/storefrontlib/src/cms-structure/services/cms-mapping.service.ts
projects/storefrontlib/src/cms-structure/services/cms-routes.service.ts
projects/storefrontlib/src/cms-structure/services/index.ts

feat: Decorate private API #4749

---

projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-as-persistent-user.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts
projects/storefrontapp-e2e-cypress/cypress/integration/mobile/checkout/checkout-as-persistent-user-mobile.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/checkout/checkout-as-persistent-user.e2e-spec.ts

Fixes: checkout e2e tests

---

projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts
projects/storefrontlib/src/cms-components/checkout/components/delivery-mode/delivery-mode.component.ts

fix: error while get preferred delivery mode #4835

---

projects/storefrontlib/src/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.html

fix: Fix Product Tabs on Product Page being unreachable via tab key 

---

projects/core/src/user/store/effects/titles.effect.ts
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.ts
projects/storefrontlib/src/cms-components/user/register/register.component.ts
projects/storefrontlib/src/shared/utils/forms/title-utils.spec.ts
projects/storefrontlib/src/shared/utils/forms/title-utils.ts
projects/storefrontlib/src/shared/utils/index.ts

GH-4584: Remove hardcoded titles, add sorting

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/order-history.ts

fix: Fix Order History test after pagination tabindex update

---

projects/storefrontlib/src/cms-components/myaccount/address-book/address-card/address-card.component.html

fix: Fix Address Book tabbing through cards

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/order-details.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

fix: Fix Failing Review Order Tabbing Test

---

projects/core/src/user/store/effects/titles.effect.ts
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.ts
projects/storefrontlib/src/cms-components/user/register/register.component.ts
projects/storefrontlib/src/shared/utils/forms/title-utils.spec.ts
projects/storefrontlib/src/shared/utils/forms/title-utils.ts
projects/storefrontlib/src/shared/utils/index.ts

GH-4584: Remove hardcoded titles, add sorting (#4883)

---

projects/storefrontlib/src/cms-components/asm/assisted-service.module.ts

GH-4896: Fix naming conflict with the ASM Component.

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/product-page.ts
projects/storefrontlib/src/cms-components/product/product-intro/product-intro.component.html

fix reviews

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/product-page-tabs.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts
projects/storefrontlib/src/shared/components/star-rating/star-rating.component.html

feat: add tests for tabs on product page

---

projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts

fix: Checkout tabbing tests failing, getting logged out after adding products to cart

---

projects/storefrontlib/src/cms-components/navigation/search-box/index.ts

fix: import for highlight pipe

---

projects/storefrontlib/src/cms-components/checkout/components/shipping-address/shipping-address.component.html
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/shipping-address.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/shipping-address.component.ts

Reverts #3642
Tests should be not commented out.

revert: "Shipping Address component clean up" 

---

projects/storefrontstyles/scss/components/content/banner/_banner.scss
projects/storefrontstyles/scss/layout/_index.scss
projects/storefrontstyles/scss/layout/page-templates/_store-finder-page.scss

Fix a breaking change in the 1.x release.
fixed #4942

Revert 100% banner images

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/product-page-tabs.ts
projects/storefrontlib/src/cms-components/product/product-tabs/product-reviews/product-reviews.component.html
projects/storefrontlib/src/cms-components/product/product-tabs/product-reviews/product-reviews.component.ts
projects/storefrontlib/src/shared/utils/accessibility/force-focus.ts

fix: improve focus in tabs on productPage

---

projects/storefrontlib/src/cms-components/product/product-tabs/product-reviews/product-reviews.component.html
projects/storefrontlib/src/cms-components/product/product-tabs/product-reviews/product-reviews.component.spec.ts
projects/storefrontlib/src/cms-components/product/product-tabs/product-reviews/product-reviews.component.ts

fix: Fix submit reviews button (should be always active)

---

projects/core/src/anonymous-consents/config/anonymous-consents-config.ts
projects/core/src/anonymous-consents/config/default-anonymous-consents-config.ts
projects/core/src/anonymous-consents/facade/anonymous-consents.service.spec.ts
projects/core/src/anonymous-consents/facade/anonymous-consents.service.ts
projects/core/src/anonymous-consents/http-interceptors/anonymous-consents-interceptor.spec.ts
projects/core/src/anonymous-consents/http-interceptors/anonymous-consents-interceptor.ts
projects/core/src/anonymous-consents/store/effects/anonymous-consents.effect.spec.ts
projects/core/src/anonymous-consents/store/effects/anonymous-consents.effect.ts
projects/core/src/user/store/effects/user-consents.effect.ts
projects/storefrontapp/src/app/app.module.ts
projects/storefrontlib/src/cms-components/anonymous-consent-management/anonymous-consent-management-banner.component.spec.ts
projects/storefrontlib/src/cms-components/anonymous-consent-management/anonymous-consent-management-banner.component.ts
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-form/consent-management-form.component.html
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-form/consent-management-form.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-form/consent-management-form.component.ts
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-management.component.html
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-management.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-management.component.ts
projects/storefrontlib/src/cms-components/navigation/footer-navigation/footer-navigation.component.ts
projects/storefrontlib/src/cms-components/user/register/register.component.html
projects/storefrontlib/src/cms-components/user/register/register.component.spec.ts
projects/storefrontlib/src/cms-components/user/register/register.component.ts
projects/storefrontlib/src/shared/components/anonymous-consents/dialog/anonymous-consents-dialog.component.html
projects/storefrontlib/src/shared/components/anonymous-consents/dialog/anonymous-consents-dialog.component.spec.ts
projects/storefrontlib/src/shared/components/anonymous-consents/dialog/anonymous-consents-dialog.component.ts
projects/storefrontlib/src/shared/components/anonymous-consents/dialog/form/anonymous-consent-form.component.html
projects/storefrontlib/src/shared/components/anonymous-consents/dialog/form/anonymous-consent-form.component.spec.ts
projects/storefrontlib/src/shared/components/anonymous-consents/dialog/form/anonymous-consent-form.component.ts

feat: required consents

---

projects/storefrontlib/src/cms-components/cms-lib.module.ts

GH-2928: Uncomment imports for tabs

---

projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.ts

fix: variant style array length conditional

---

projects/assets/src/translations/en/product.ts
projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.html
projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.spec.ts
projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.html
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.ts

Variant selector UX improvement

---

projects/storefrontlib/src/cms-components/checkout/components/checkout-progress/checkout-progress.component.html
projects/storefrontlib/src/cms-components/checkout/components/checkout-progress/checkout-progress.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/checkout-progress/checkout-progress.component.ts

fix: Fix tabbing on checkout stepsz

---

projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item/cart-item.component.html

fix: Add to cart modal: Price label should be Item Price or Price 

---

projects/storefrontstyles/scss/themes/calydon/components/_index.scss
projects/storefrontstyles/scss/themes/calydon/components/product/_index.scss
projects/storefrontstyles/scss/themes/calydon/components/product/_product-view.scss

add cursor pointer

---

projects/schematics/src/add-ssr/index.ts

fix: remove unnecessary ssr configuration

---

projects/storefrontstyles/scss/themes/calydon/components/_index.scss
projects/storefrontstyles/scss/themes/calydon/components/content/_index.scss
projects/storefrontstyles/scss/themes/calydon/components/content/navigation/_index.scss
projects/storefrontstyles/scss/themes/calydon/components/content/navigation/_navigation-ui.scss

fix: No visual focus feedback for menu items on desktop

---

projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-management.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-management.component.ts

feat: pre-release cleanup

---

projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.spec.ts
projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.ts

fix (storefront): disable add to cart on PLP when there's no stock

---

projects/core/src/anonymous-consents/facade/anonymous-consents.service.spec.ts
projects/core/src/anonymous-consents/http-interceptors/anonymous-consents-interceptor.spec.ts
projects/core/src/anonymous-consents/http-interceptors/anonymous-consents-interceptor.ts
projects/core/src/anonymous-consents/store/anonymous-consents-state.ts
projects/core/src/anonymous-consents/store/anonymous-consents-store.module.ts
projects/core/src/anonymous-consents/store/effects/anonymous-consents.effect.spec.ts
projects/core/src/anonymous-consents/store/effects/anonymous-consents.effect.ts
projects/core/src/anonymous-consents/store/selectors/anonymous-consent-templates.selectors.spec.ts
projects/core/src/anonymous-consents/store/selectors/anonymous-consents.selectors.spec.ts
projects/core/src/anonymous-consents/store/selectors/feature.selector.ts
projects/core/src/features-config/config/features-config.ts
projects/storefrontapp/src/app/app.module.ts
projects/storefrontlib/src/cms-components/anonymous-consent-management/anonymous-consent-management-banner.component.html
projects/storefrontlib/src/cms-components/anonymous-consent-management/anonymous-consent-management-banner.component.spec.ts
projects/storefrontlib/src/cms-components/anonymous-consent-management/anonymous-consent-management-banner.component.ts
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-form/consent-management-form.component.html
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-form/consent-management-form.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-form/consent-management-form.component.ts
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-management.component.html
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-management.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-management.component.ts
projects/storefrontlib/src/cms-components/navigation/footer-navigation/footer-navigation.component.spec.ts
projects/storefrontlib/src/cms-components/navigation/footer-navigation/footer-navigation.component.ts
projects/storefrontlib/src/cms-components/user/register/register.component.html
projects/storefrontlib/src/cms-components/user/register/register.component.spec.ts
projects/storefrontlib/src/cms-components/user/register/register.component.ts
projects/storefrontlib/src/feature-toggles.ts

feat: convert feature level toggle to named feature for anonymous consents 

---

projects/core/src/cms/facade/page-meta.service.ts

fix: TS warning for constructor dependency of PageMetaService

---

projects/core/src/product/services/category-page-meta.resolver.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/product-details.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/product-details.e2e-spec.ts
projects/storefrontapp/src/app/app.module.ts

fix: e2e test for variant selector functionality

---

projects/storefrontlib/src/recipes/b2c-storefront.module.ts
projects/storefrontlib/src/recipes/config/optional-layouts/plp-accessibility-layout-config.ts

feat: add optional plp a11y layout

---

projects/assets/src/translations/en/product.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.html

GH-4573: Add translation to variants

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/product-list.ts
projects/storefrontlib/src/cms-components/product/product-list/product-facet-navigation/product-facet-navigation.component.html
projects/storefrontlib/src/recipes/config/b2c-layout-config.ts

fix: productList tests

---

projects/storefrontapp/src/app/app.module.ts

Revert app.module config

---

projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.html
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.ts

fix: disable select label option in variant size component

---

projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.html
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.ts

fix: selectedStyle refactor

---

projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.html
projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.spec.ts
projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.ts
projects/storefrontlib/src/cms-components/product/product-list/container/product-list.component.spec.ts
projects/storefrontlib/src/cms-components/product/product-list/container/product-scroll/product-scroll.component.spec.ts
projects/storefrontlib/src/cms-components/product/product-list/product-grid-item/product-grid-item.component.html
projects/storefrontlib/src/cms-components/product/product-list/product-grid-item/product-grid-item.component.spec.ts
projects/storefrontlib/src/cms-components/product/product-list/product-list-item/product-list-item.component.html
projects/storefrontlib/src/cms-components/product/product-list/product-list-item/product-list-item.component.spec.ts

PLP "add to cart" button makes call to API for every list item

---

projects/storefrontlib/src/shared/config/index.ts
projects/storefrontlib/src/shared/index.ts

fix (storefront): export view config in public library

---

projects/storefrontapp/src/app/app.module.ts
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-form/consent-management-form.component.html
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-form/consent-management-form.component.ts
projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-management.component.html
projects/storefrontlib/src/shared/components/anonymous-consents/dialog/anonymous-consent-dialog.component.html
projects/storefrontlib/src/shared/components/anonymous-consents/dialog/anonymous-consent-dialog.component.spec.ts
projects/storefrontlib/src/shared/components/anonymous-consents/dialog/anonymous-consent-dialog.component.ts
projects/storefrontstyles/scss/_sparta-theme.scss
projects/storefrontstyles/scss/components/myaccount/_consent-management-form.scss
projects/storefrontstyles/scss/components/myaccount/_index.scss

feat: show consent template name

---

projects/storefrontlib/src/cms-components/myaccount/consent-management/components/consent-form/consent-management-form.component.html

feat: display template description in a new row

---

projects/storefrontstyles/scss/components/product/search/_searchbox.scss

fix (styles): Use fixed overlay to avoid scrolling away from the overlay

---

projects/core/src/model/product.model.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.html
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.spec.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.module.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/size-selector/size-selector.component.html
projects/storefrontlib/src/cms-components/product/product-variant-selector/size-selector/size-selector.component.spec.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/size-selector/size-selector.component.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/size-selector/size-selector.module.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/style-selector/style-selector.component.html
projects/storefrontlib/src/cms-components/product/product-variant-selector/style-selector/style-selector.component.spec.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/style-selector/style-selector.component.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/style-selector/style-selector.module.ts

WIP: Variants components refactoring

---

projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.spec.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.ts
projects/storefrontstyles/scss/_page-template.scss

fix: auto redirect for selecting available style with size

---

projects/core/src/config/config-validator/config-validator.module.ts
projects/core/src/i18n/i18next/i18next-init.ts
projects/core/src/site-context/providers/context-service-providers.ts

multisite fixes: wait for whole i18next config to be stable and swap initialization of lang and curr

---

projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.html
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/size-selector/size-selector.component.html
projects/storefrontlib/src/cms-components/product/product-variant-selector/size-selector/size-selector.component.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/style-selector/style-selector.component.html
projects/storefrontlib/src/cms-components/product/product-variant-selector/style-selector/style-selector.component.ts

Variants refactoring

---

projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.spec.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/size-selector/size-selector.component.spec.ts

fix: variant select unit tests

---

projects/core/src/organization/facade/budget.service.ts
projects/core/src/organization/store/actions/budget.action.ts
projects/core/src/organization/store/effects/budget.effect.ts
projects/core/src/organization/store/organization-state.ts
projects/core/src/organization/store/reducers/budget.reducer.ts
projects/core/src/organization/store/reducers/index.ts
projects/core/src/organization/store/selectors/budget.selector.ts
projects/core/src/organization/utils/budgets.ts
projects/storefrontlib/src/cms-components/navigation/breadcrumb/breadcrumb.component.ts

feat: New store structure

---

projects/storefrontlib/src/shared/components/anonymous-consents/anonymous-consents.module.ts
projects/storefrontlib/src/shared/components/anonymous-consents/dialog/anonymous-consent-dialog.component.html
projects/storefrontlib/src/shared/components/anonymous-consents/dialog/anonymous-consent-dialog.component.spec.ts
projects/storefrontlib/src/shared/components/anonymous-consents/dialog/anonymous-consent-dialog.component.ts

feat: add spinner to anonymous consents dialog

---

projects/storefrontstyles/scss/components/myaccount/anonymous-consent/_anonymous-consent-dialog.scss

GH-5373 adjust padding for small mobile devices

---

projects/storefrontlib/src/cms-components/product/index.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/guards/index.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/guards/product-variant.guard.spec.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/guards/product-variant.guard.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.module.ts

fix: variant redirect guard

---

projects/assets/src/translations/en/product.ts
projects/assets/src/translations/translation-chunks-config.ts
projects/storefrontlib/src/cms-components/cart/add-to-wishlist/add-to-wish-list.component.html
projects/storefrontlib/src/cms-components/cart/add-to-wishlist/add-to-wish-list.component.spec.ts
projects/storefrontlib/src/cms-components/cart/add-to-wishlist/add-to-wish-list.component.ts
projects/storefrontlib/src/cms-components/cart/add-to-wishlist/add-to-wish-list.module.ts
projects/storefrontlib/src/cms-components/cart/cart.module.ts

[GH-5232] Add to wishlist component

---

projects/core/src/product/services/product-page-meta.resolver.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/product-variant-selector.component.ts
projects/storefrontlib/src/cms-structure/page/page-layout/page-layout.service.ts

Introduce robots NOINDEX for non purchasable products

---

projects/core/src/cart/facade/wish-list.service.spec.ts
projects/core/src/cart/facade/wish-list.service.ts

Add and remove from wish list methods in facade

---

projects/storefrontstyles/scss/components/checkout/_promotions.scss

GH-1638: Set the line height for promotion elem

---

projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-form/payment-form.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-form/payment-form.component.ts

fix: Add Payment Method Continue button should not be disabled

---

projects/assets/package.json
projects/core/package.json
projects/storefrontlib/package.json
projects/storefrontstyles/package.json

Release/1.3.0 

---

projects/assets/src/translations/en/product.ts
projects/core/src/cart/facade/wish-list.service.spec.ts
projects/core/src/cart/facade/wish-list.service.ts
projects/core/src/cart/store/effects/wish-list.effect.ts
projects/core/src/cart/store/selectors/multi-cart.selector.ts
projects/storefrontlib/src/cms-components/cart/add-to-wishlist/add-to-wish-list.component.html
projects/storefrontlib/src/cms-components/cart/add-to-wishlist/add-to-wish-list.component.spec.ts
projects/storefrontlib/src/cms-components/cart/add-to-wishlist/add-to-wish-list.component.ts
projects/storefrontlib/src/cms-components/cart/add-to-wishlist/add-to-wish-list.module.ts
projects/storefrontlib/src/cms-components/misc/icon/fontawesome-icon.config.ts
projects/storefrontlib/src/cms-components/misc/icon/icon.model.ts
projects/storefrontstyles/scss/components/cart/_add-to-wishlist.scss
projects/storefrontstyles/scss/components/cart/_index.scss
projects/storefrontstyles/scss/layout/page-templates/_product-detail.scss

Functional Add To Wish list

---

projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item/cart-item.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/address-book/address-book.component.spec.ts

test: add testing cases for cart item and address book (GH-5443)

---

ci-scripts/e2e-cypress.sh

ci: check for warning in production build

---

projects/assets/src/translations/en/product.ts
projects/storefrontapp/src/environments/environment.ts
projects/storefrontlib/src/cms-components/cart/add-to-wishlist/add-to-wish-list.component.html
projects/storefrontlib/src/cms-components/misc/icon/fontawesome-icon.config.ts
projects/storefrontlib/src/cms-components/misc/icon/icon.model.ts
projects/storefrontstyles/scss/components/cart/_add-to-wishlist.scss

Add to Wish List styling update

---

projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.ts

GH-4908: Removed assignment to variable sorting operation

---

projects/storefrontlib/src/cms-components/user/register/register.component.ts

fix: Remove sorting operation assignment to variable in register form

---

projects/storefrontapp-e2e-cypress/cypress/helpers/applied-promotions.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/applied-promotions.e2e-spec.ts

test: applied promotions happy paths

---

projects/storefrontlib/src/cms-components/product/product-list/index.ts
projects/storefrontlib/src/cms-components/product/product-list/product-list.module.ts

fix: add missing export for the product-scroll component

---

projects/storefrontlib/src/layout/main/storefront.component.html

GH-5606 develop

---

projects/core/src/occ/config-loader/index.ts

OccConfigLoaderService
OccSitesConfigLoader
closes GH-5570

fix: missing exports of services for site auto-config

---

projects/storefrontlib/src/shared/directives/auto-focus/index.ts
projects/storefrontlib/src/shared/directives/index.ts
projects/storefrontlib/src/shared/directives/only-number/index.ts

AutoFocusDirectiveModule not exported #5490 (1.3fix)

---

projects/assets/src/translations/en/product.ts
projects/storefrontlib/src/cms-components/cart/add-to-wishlist/add-to-wish-list.component.html
projects/storefrontlib/src/cms-components/cart/add-to-wishlist/add-to-wish-list.component.spec.ts
projects/storefrontlib/src/cms-components/cart/add-to-wishlist/add-to-wish-list.module.ts
projects/storefrontstyles/scss/components/cart/_add-to-wishlist.scss

Add to wish list anonymous, redirect to login

---

projects/storefrontstyles/scss/themes/calydon/components/product/list/_product-list.scss

fix: Pointer on Back To Top button should be a hand (GH-4360) (#5500)

---

projects/storefrontlib/src/cms-components/product/product-list/index.ts
projects/storefrontlib/src/cms-components/product/product-list/product-list.module.ts

add missing export for the product-scroll component

---

projects/storefrontstyles/scss/themes/calydon/components/product/_index.scss
projects/storefrontstyles/scss/themes/calydon/components/product/details/_index.scss
projects/storefrontstyles/scss/themes/calydon/components/product/details/_product-images.scss

fix: Spacing issues with thumbnail for product with carousel (GH-4361)

---

projects/core/src/site-context/providers/index.ts
projects/core/src/site-context/providers/site-context-params-providers.ts
projects/core/src/site-context/services/site-context-routes-handler.ts

fix: update url after manual context change, when using auto site-config (for 1.3.1)

---

projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item/cart-item.component.html
projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item/cart-item.component.spec.ts
projects/storefrontstyles/scss/components/cart/_cart-item.scss

GH-5557: Display variant properties in cart item component

---

projects/storefrontlib/src/cms-components/navigation/navigation/navigation.service.spec.ts
projects/storefrontlib/src/cms-components/navigation/navigation/navigation.service.ts

fix: Avoid empty navigation nodes in the UI

---

projects/core/src/user/facade/user-address.service.ts
projects/core/src/user/facade/user-consent.service.ts
projects/core/src/user/facade/user-order.service.ts
projects/core/src/user/facade/user-payment.service.ts
projects/core/src/user/facade/user.service.ts

closes GH-5543
(cherry picked from commit 1c15ccd39cab966dc487e4456e1a90687768e0c2)

GH-5543 - cherry pick from release/1.3.x to develop

---

projects/core/src/user/facade/user-address.service.ts
projects/core/src/user/facade/user-consent.service.ts
projects/core/src/user/facade/user-order.service.ts
projects/core/src/user/facade/user-payment.service.ts
projects/core/src/user/facade/user.service.ts

GH-5658 for 1.3.1

---

projects/core/src/user/facade/user-address.service.ts
projects/core/src/user/facade/user-consent.service.ts
projects/core/src/user/facade/user-order.service.ts
projects/core/src/user/facade/user-payment.service.ts
projects/core/src/user/facade/user.service.ts

GH-5658 for 1.3.x

---

projects/storefrontlib/src/cms-components/wish-list/components/wish-list-item/wish-list-item.component.html
projects/storefrontlib/src/cms-components/wish-list/components/wish-list/wish-list.component.html
projects/storefrontstyles/scss/components/wish-list/_wish-list.scss

Removed quantity from wish list

---

projects/core/src/cart/facade/wish-list.service.spec.ts
projects/core/src/cart/facade/wish-list.service.ts
projects/core/src/cart/store/selectors/multi-cart.selector.ts

Using multi-cart serivce

---

projects/assets/src/translations/en/common.ts
projects/storefrontlib/src/cms-components/user/register/register.component.ts

fix: Registration form not providing feedback on submit

---

projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.ts

fix: Validation messages for address form

---

projects/assets/package.json
projects/core/package.json
projects/storefrontlib/package.json
projects/storefrontstyles/package.json

Release 1.4.0-next-0 #5722

---

projects/storefrontlib/src/cms-components/cart/add-to-wishlist/add-to-wish-list.component.html
projects/storefrontlib/src/cms-components/cart/add-to-wishlist/add-to-wish-list.component.spec.ts

Remove link when no stock

---

projects/assets/src/translations/en/product.ts
projects/storefrontlib/src/cms-components/product/product-variant-selector/size-selector/size-selector.component.html
projects/storefrontstyles/scss/components/product/index.scss

fix: remove size label for size variant selector

---

projects/storefrontapp/src/app/app.module.ts
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-actions/order-detail-actions.component.html
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-actions/order-detail-actions.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-actions/order-detail-actions.component.ts
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-headline/order-detail-headline.component.html
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-headline/order-detail-headline.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-details.module.ts

feature/GH-4659: make cancel/return buttons into action component

---

projects/storefrontapp/src/styles.scss
projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item/cart-item.component.html
projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item/cart-item.component.spec.ts
projects/storefrontstyles/scss/layout/page-templates/_product-detail.scss
projects/storefrontstyles/scss/themes/calydon/_index.scss
projects/storefrontstyles/scss/themes/calydon/layout/_index.scss
projects/storefrontstyles/scss/themes/calydon/layout/page-templates/_product-detail.scss

Handle reported breaking changes in pull request for epic

---

projects/core/src/cart/facade/active-cart.service.spec.ts
projects/core/src/cart/facade/active-cart.service.ts
projects/core/src/cart/store/actions/multi-cart.action.spec.ts
projects/core/src/cart/store/actions/multi-cart.action.ts
projects/core/src/cart/store/effects/cart.effect.ts
projects/core/src/cart/store/reducers/multi-cart.reducer.spec.ts
projects/core/src/cart/store/reducers/multi-cart.reducer.ts

fix: Emit empty cart when creating/merging active cart

---

projects/assets/src/translations/en/cart.ts
projects/storefrontlib/src/cms-components/wish-list/components/wish-list-item/wish-list-item.component.html
projects/storefrontlib/src/cms-components/wish-list/components/wish-list-item/wish-list-item.component.spec.ts
projects/storefrontstyles/scss/components/wish-list/_wish-list-item.scss

A product that is in stock can be added to the wish list. If that product goes out of stock while it is in the wish list the add to cart option should not be visible but it should display "Out of stock"

Wish list displays out of stock

---

projects/schematics/package.json

Release schematics@1.3.0 #5825

---

projects/core/src/product/facade/product.service.ts
projects/core/src/product/store/effects/product.effect.ts
projects/core/src/util/withdraw-on.spec.ts
projects/core/src/util/withdraw-on.ts

fix: Proper product loading on context switch behavior

---

projects/storefrontlib/src/cms-components/myaccount/order/order-history/order-history.module.ts
projects/storefrontlib/src/cms-components/myaccount/order/return-request-detail/return-request-overview/return-request-overview.component.spec.ts

feature/GH-5841: apply AuthGuard to page

---

projects/storefrontlib/src/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.spec.ts
projects/storefrontlib/src/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts
projects/storefrontlib/src/cms-components/myaccount/order/return-request-detail/return-request-overview/return-request-overview.component.html
projects/storefrontlib/src/cms-components/myaccount/order/return-request-detail/return-request-overview/return-request-overview.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/order/return-request-detail/return-request-overview/return-request-overview.component.ts
projects/storefrontlib/src/cms-components/myaccount/order/return-request-detail/return-request.service.spec.ts
projects/storefrontlib/src/cms-components/myaccount/order/return-request-detail/return-request.service.ts

feature/GH-5813: back to return request list

---

projects/assets/src/translations/en/common.ts

feature/GH-5879: change RMA to return number

---

projects/assets/src/translations/en/my-account.ts
projects/storefrontlib/src/cms-components/myaccount/order/cancellations-returns/cancel-order-confirmation/cancel-order-confirmation.component.html
projects/storefrontlib/src/cms-components/myaccount/order/cancellations-returns/return-order-confirmation/return-order-confirmation.component.html

feature/GH-5881: Add note about update delay after submitting cancel/return

---

projects/storefrontlib/src/cms-components/myaccount/order/cancellations-returns/cancel-or-return.service.spec.ts
projects/storefrontlib/src/cms-components/myaccount/order/cancellations-returns/cancel-or-return.service.ts
projects/storefrontlib/src/cms-components/myaccount/order/cancellations-returns/cancel-order-confirmation/cancel-order-confirmation.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/order/cancellations-returns/cancel-order-confirmation/cancel-order-confirmation.component.ts
projects/storefrontlib/src/cms-components/myaccount/order/cancellations-returns/cancel-order-confirmation/cancel-order-confirmation.module.ts
projects/storefrontlib/src/cms-components/myaccount/order/cancellations-returns/cancel-order/cancel-order.module.ts
projects/storefrontlib/src/cms-components/myaccount/order/cancellations-returns/return-order-confirmation/return-order-confirmation.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/order/cancellations-returns/return-order-confirmation/return-order-confirmation.component.ts
projects/storefrontlib/src/cms-components/myaccount/order/cancellations-returns/return-order-confirmation/return-order-confirmation.module.ts
projects/storefrontlib/src/cms-components/myaccount/order/cancellations-returns/return-order/return-order.module.ts

feature/GH-5816: keep entry input when back from confirmation page

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontlib/src/cms-components/navigation/search-box/search-box.component.html
projects/storefrontlib/src/cms-components/navigation/search-box/search-box.component.spec.ts
projects/storefrontlib/src/cms-components/navigation/search-box/search-box.component.ts
projects/storefrontstyles/scss/components/product/search/_searchbox.scss

feat: Search Box Auxiliary key navigation

---

projects/storefrontlib/src/cms-structure/page/page-layout/page-layout.service.spec.ts
projects/storefrontlib/src/cms-structure/page/page-layout/page-layout.service.ts

fix: error occurred for page fold when page layout is not configured (5907)

---

projects/storefrontlib/src/cms-structure/outlet/outlet.directive.ts
projects/storefrontlib/src/cms-structure/page/slot/page-slot.component.spec.ts
projects/storefrontlib/src/cms-structure/page/slot/page-slot.component.ts

fix: fixed breaking change in page slot introduced in 1.4

---

projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.html

fix: remove debug info from template

---

projects/core/src/user/store/effects/user-orders.effect.spec.ts
projects/core/src/user/store/effects/user-orders.effect.ts

fix: Clear user orders on language change action

---

projects/core/src/occ/services/loading-scopes.service.spec.ts
projects/core/src/occ/services/loading-scopes.service.ts
projects/core/src/product/services/product-loading.service.spec.ts
projects/core/src/product/services/product-loading.service.ts

fix: Improve unit test coverage for product loading (#5933)

---

projects/core/src/anonymous-consents/store/selectors/anonymous-consent-templates.selectors.ts
projects/storefrontlib/src/cms-components/user/register/register.component.ts

fix: adjust anonymous consent template selector (#5904)

---

projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.html
projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.ts
projects/storefrontstyles/scss/components/content/navigation/_navigation-ui.scss

feat: Navigate categories with aux keys

---

projects/storefrontlib/src/shared/components/card/card.component.html
projects/storefrontstyles/scss/components/misc/card/_card.scss

fix: Fix styling focus and keypress on card links

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/wishlist.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts
projects/storefrontlib/src/cms-components/wish-list/components/wish-list-item/wish-list-item.component.html

fix: Skip product img with tab and add tabbing order test for wishlist

---

projects/core/src/occ/adapters/product/default-occ-product-config.ts
projects/core/src/occ/adapters/product/product-occ-config.ts
projects/core/src/occ/adapters/product/product-occ.module.ts
projects/core/src/occ/config/loading-scopes-config.ts
projects/core/src/occ/config/occ-config.ts
projects/core/src/product/facade/product.service.ts
projects/core/src/product/model/index.ts
projects/core/src/product/model/product-scope.ts
projects/core/src/product/services/product-page-meta.resolver.ts
projects/storefrontlib/src/cms-components/myaccount/my-interests/my-interests.component.ts
projects/storefrontlib/src/cms-components/product/carousel/product-carousel/product-carousel.component.ts
projects/storefrontlib/src/cms-components/product/current-product.service.ts

fix: Add type-safety for product loading (scopes and maxAge) (#5961)

---

.gitignore
projects/assets/package.json
projects/core/.release-it.json
projects/core/package.json
projects/storefrontapp/src/app/app.module.ts
projects/storefrontlib/package.json
projects/storefrontstyles/package.json

Release/1.5.0 next.1

---

projects/storefrontlib/src/cms-structure/outlet/outlet.directive.ts

fix: Rerender outlet on input change

---

projects/storefrontlib/src/cms-structure/outlet/outlet.directive.ts

fix: Rerender outlet on input change (#5977)

---

projects/schematics/README.md
projects/schematics/src/add-spartacus/index.ts
projects/schematics/src/add-spartacus/schema.json

feat: schematics bump for 1.4 release

---

projects/storefrontlib/src/cms-components/cart/add-to-cart/added-to-cart-dialog/added-to-cart-dialog.component.html
projects/storefrontlib/src/cms-components/cart/add-to-cart/added-to-cart-dialog/added-to-cart-dialog.component.ts
projects/storefrontlib/src/cms-components/cart/cart-details/cart-details.component.html
projects/storefrontlib/src/cms-components/cart/cart-details/cart-details.component.ts
projects/storefrontlib/src/cms-components/checkout/components/review-submit/review-submit.component.html
projects/storefrontlib/src/cms-components/checkout/components/review-submit/review-submit.component.ts
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-detail-items.component.html
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-detail-items.component.ts
projects/storefrontlib/src/cms-components/order-confirmation/components/order-confirmation-items/order-confirmation-items.component.html
projects/storefrontlib/src/cms-components/order-confirmation/components/order-confirmation-items/order-confirmation-items.component.ts

GH-6005: Bump up feature level

---

projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-details.module.ts
projects/storefrontlib/src/cms-structure/routing/default-routing-config.ts

fix: Make guest order route configurable #6017

---

projects/storefrontlib/src/cms-components/organization/budgets/budget-form/budget-form.component.html

fix: Budget form - Change the order of buttons in mobile view

---

projects/storefrontlib/src/cms-components/myaccount/order/amend-order/cancellations/order-cancellation.service.spec.ts
projects/storefrontlib/src/cms-components/myaccount/order/amend-order/cancellations/order-cancellation.service.ts
projects/storefrontlib/src/cms-components/myaccount/order/amend-order/returns/order-return.service.spec.ts
projects/storefrontlib/src/cms-components/myaccount/order/amend-order/returns/order-return.service.ts

Only send amended order entries

---

projects/storefrontapp-e2e-cypress/cypress/helpers/order-cancellations-returns.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/my-account/order-cancellations.e2e-spec.ts

test: e2e tests for order cancellations

---

projects/core/src/global-message/store/effects/global-message.effect.ts

Backport of #6007 for 1.4.x
Closes #4829

fix: Global Message timeout blocks rendering of SSR application

---

projects/storefrontlib/src/cms-components/product/product-variant-selector/style-icons/style-icons.component.scss
projects/storefrontstyles/scss/components/product/list/_product-grid-item.scss

PLP grid variant icons align fix

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/add-to-cart.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/cart.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/consent-management.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/header.ts
projects/storefrontapp-e2e-cypress/cypress/support/index.js
projects/storefrontstyles/scss/components/content/navigation/_navigation-ui.scss

fix: improve e2e tests

---

projects/core/src/occ/adapters/product/default-occ-product-config.ts
projects/core/src/occ/adapters/product/product-occ-config.ts
projects/core/src/product/model/product-scope.ts
projects/storefrontlib/src/cms-components/product/current-product.service.spec.ts
projects/storefrontlib/src/cms-components/product/current-product.service.ts
projects/storefrontlib/src/cms-components/product/product-tabs/product-attributes/product-attributes.component.ts

fix: use product attribute scope

---

projects/core/src/occ/adapters/product/default-occ-product-config.ts
projects/core/src/occ/adapters/product/product-occ-config.ts
projects/core/src/product/model/product-scope.ts
projects/storefrontlib/src/cms-components/product/current-product.service.spec.ts
projects/storefrontlib/src/cms-components/product/current-product.service.ts
projects/storefrontlib/src/cms-components/product/product-tabs/product-attributes/product-attributes.component.ts

fix: use product attribute and variant scopes

---

projects/storefrontapp/src/environments/environment.ts
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-consigned-entries/order-consigned-entries.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-detail-items.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-detail-items.component.ts

chore: small refactor / not breaking current fix

---

projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.spec.ts
projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-consigned-entries/order-consigned-entries.component.html
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-consigned-entries/order-consigned-entries.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-consigned-entries/order-consigned-entries.component.ts
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-detail-items.component.html

feature/GH-6123_1.4: disply consignment quatity for each consignment entry

---

projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.spec.ts
projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-detail-items.component.html
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-detail-items.component.ts

feature/GH-6123: display consignment quantity for consignment entry

---

projects/storefrontstyles/scss/theme/sparta/_fonts.scss

fix: Always use https for fonts instead of current host protocol

---

projects/core/src/cart/facade/active-cart.service.ts
projects/core/src/cart/facade/multi-cart.service.spec.ts
projects/core/src/cart/facade/multi-cart.service.ts
projects/core/src/cart/store/actions/multi-cart.action.spec.ts
projects/core/src/cart/store/actions/multi-cart.action.ts
projects/core/src/cart/store/actions/wish-list.action.spec.ts
projects/core/src/cart/store/actions/wish-list.action.ts
projects/core/src/cart/store/effects/cart.effect.spec.ts
projects/core/src/cart/store/effects/cart.effect.ts
projects/core/src/cart/store/effects/multi-cart.effect.spec.ts
projects/core/src/cart/store/effects/multi-cart.effect.ts
projects/core/src/cart/store/reducers/multi-cart.reducer.spec.ts
projects/core/src/cart/store/reducers/multi-cart.reducer.ts
projects/core/src/cart/utils/utils.spec.ts
projects/core/src/cart/utils/utils.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/cart.ts
projects/storefrontapp-e2e-cypress/cypress/integration/mobile/cart-mobile.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/cart.e2e-spec.ts

fix: Support creating multiple carts at the same time (#6099)

---

projects/core/src/cart/facade/index.ts

feat: Add MultiCartService to public API

---

projects/storefrontapp-e2e-cypress/cypress/helpers/applied-promotions.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-as-persistent-user.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/payment-methods.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/site-context-selector.ts

fix: adjust delivery mode node id

---

projects/storefrontapp-cds-integration/src/environments/environment.ci.ts

Update environment.ci.ts in the cds shell app (GH-6176)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/added-to-cart-modal.ts

test: Added to cart modal e2e - assertion on data has changed (GH-6144)

---

projects/core/src/cart/facade/wish-list.service.spec.ts
projects/core/src/cart/facade/wish-list.service.ts
projects/core/src/cart/store/actions/wish-list.action.spec.ts
projects/core/src/cart/store/actions/wish-list.action.ts
projects/core/src/cart/store/effects/wish-list.effect.spec.ts
projects/core/src/cart/store/effects/wish-list.effect.ts

GH-6178: Change wish list name

---

projects/core/src/anonymous-consents/facade/anonymous-consents.service.ts
projects/storefrontlib/src/shared/components/anonymous-consents/dialog/anonymous-consent-dialog.component.ts

fix: Register & Anonymous consents e2e tests failing #6153 #6150

---

projects/storefrontapp-e2e-cypress/cypress/helpers/cart.ts

test: cart e2e tests failing (GH-6146)

---

projects/core/src/smart-edit/services/smart-edit.service.spec.ts
projects/core/src/smart-edit/services/smart-edit.service.ts

feature/GH-6107: make smartedit work with default routing config

---

projects/storefrontapp-e2e-cypress/cypress/integration/mobile/checkout/checkout-flow-mobile.e2e-spec.ts

fix: remove unnecessary test regarding order history

---

projects/storefrontapp-e2e-cypress/cypress/helpers/product-search.ts

test: Smoke test - product search e2e test failing (GH-6245)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/asm.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-forms.ts
projects/storefrontapp-e2e-cypress/cypress/integration/mobile/checkout/checkout-flow-mobile.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/checkout/checkout-as-guest.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/smoke/checkout-flow.e2e-spec.ts

GH-6145: Fix ASM e2e tests and other e2e tests

---

projects/core/src/cart/facade/active-cart.service.spec.ts
projects/core/src/cart/facade/active-cart.service.ts
projects/core/src/cart/facade/multi-cart.service.spec.ts
projects/core/src/cart/facade/multi-cart.service.ts
projects/core/src/cart/store/effects/cart.effect.spec.ts
projects/core/src/cart/store/effects/cart.effect.ts

fix: Provide temp cart id in merge action

---

projects/core/src/cart/facade/active-cart.service.spec.ts
projects/core/src/cart/facade/active-cart.service.ts
projects/core/src/cart/facade/multi-cart.service.spec.ts
projects/core/src/cart/facade/multi-cart.service.ts
projects/core/src/cart/store/effects/cart.effect.spec.ts
projects/core/src/cart/store/effects/cart.effect.ts

fix: Provide temp cart id in merge action (#6250)

---

projects/storefrontapp-e2e-cypress/cypress/integration/mobile/my-account/order-history-orders-flow-mobile.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/my-account/order-history-orders-flow.e2e-spec.ts

Closes GH-6151
Skipping the test because we have no solution to fix orders to be instantly set with oms

test: order history with order flow e2e test failing (GH-6151)

---

projects/storefrontapp-e2e-cypress/cypress/integration/regression/site-context/currency/currency-checkout-page.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/site-context/language/language-my-account-pages.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/sample-data/checkout-flow.ts
projects/storefrontapp/src/environments/environment.ts

Site Context e2e test failing (GH-6156)

---

projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-pricing-flow.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-product-type-flow.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-rating-flow.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-store-flow.ts

test: product search e2e tests failing (GH-6267)

---

projects/core/src/personalization/config/default-personalization-config.ts
projects/core/src/personalization/config/personalization-config.ts
projects/core/src/personalization/index.ts
projects/core/src/personalization/model/personalization-context.model.ts
projects/core/src/personalization/services/personalization-context.service.spec.ts
projects/core/src/personalization/services/personalization-context.service.ts

feature/GH-6072: expose personalization context in Spartacus

---

projects/core/src/product/services/product-loading.service.spec.ts
projects/core/src/product/services/product-loading.service.ts

fix: Fix partial emissions of product scopes

---

projects/core/src/product/services/product-loading.service.spec.ts
projects/core/src/product/services/product-loading.service.ts

Backport of #6328 to 1.4.x
Closes #6327

fix: Fix partial emissions of product scopes (#6328)

---

README.md

Add link to Stack Overflow

---

projects/core/src/occ/services/loading-scopes.service.spec.ts
projects/core/src/occ/services/loading-scopes.service.ts

fix: Fix proper merging order of included scopes

---

projects/storefrontstyles/scss/cxbase/blocks/forms.scss

- removing vendor prefixes while on it

GH-4324 transferring cross-browser fixes from develop

---

projects/core/src/user/facade/user.service.spec.ts
projects/core/src/user/facade/user.service.ts

fix: Prevent 401 on loading user details for anonymous users

---

projects/storefrontapp-e2e-cypress/cypress/helpers/cart-coupon.ts
projects/storefrontapp-e2e-cypress/cypress/integration/mobile/coupon/coupon.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/coupon/coupon.e2e-spec.ts

fix: change target label price node order history verification

---

projects/assets/src/translations/en/my-account.ts
projects/storefrontlib/src/cms-components/myaccount/order/cancellations-returns/cancel-or-return-items/cancel-or-return-items.component.ts

fix: prevent cancel for completed order

---

projects/core/src/cms/store/selectors/component.selectors.spec.ts
projects/core/src/cms/store/selectors/component.selectors.ts

fix: cms components factory selector

---

projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.html
projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.spec.ts
projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.ts
projects/storefrontstyles/scss/components/content/navigation/_navigation-ui.scss

fix: navigations with large amount of childs will overflow on mobile

---

projects/storefrontapp-cds-integration/src/app/app.module.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/navigation.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/vendor/cds/cds.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/vendor/cds/profile-tag.ts
projects/storefrontapp-e2e-cypress/cypress/integration/vendor/cds/profile-tag.e2e-spec.ts

The initial integration tests for Profiletag have been added.
Closes GH-6071

test: add initial integration tests for profiletag (GH-6071)

---

projects/core/src/occ/adapters/user/default-occ-user-config.ts
projects/core/src/occ/adapters/user/occ-user-order.adapter.spec.ts
projects/core/src/occ/adapters/user/occ-user-order.adapter.ts
projects/core/src/user/connectors/order/user-order.adapter.ts
projects/core/src/user/connectors/order/user-order.connector.spec.ts
projects/core/src/user/connectors/order/user-order.connector.ts
projects/core/src/user/facade/user-order.service.spec.ts
projects/core/src/user/facade/user-order.service.ts
projects/core/src/user/store/actions/consignment-tracking.action.spec.ts
projects/core/src/user/store/actions/consignment-tracking.action.ts
projects/core/src/user/store/effects/consignment-tracking.effect.spec.ts
projects/core/src/user/store/effects/consignment-tracking.effect.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/consignment-tracking.ts
projects/storefrontapp/src/environments/environment.ts

Closes GH-6149
contains request to consignment fix and e2e improvements

fix: consignment tracking request fix and e2e test (GH-6149)

---

projects/core/src/occ/adapters/user/default-occ-user-config.ts
projects/core/src/occ/adapters/user/occ-user-order.adapter.spec.ts
projects/core/src/occ/adapters/user/occ-user-order.adapter.ts
projects/core/src/user/connectors/order/user-order.adapter.ts
projects/core/src/user/connectors/order/user-order.connector.spec.ts
projects/core/src/user/connectors/order/user-order.connector.ts
projects/core/src/user/facade/user-order.service.spec.ts
projects/core/src/user/facade/user-order.service.ts
projects/core/src/user/store/actions/consignment-tracking.action.spec.ts
projects/core/src/user/store/actions/consignment-tracking.action.ts
projects/core/src/user/store/effects/consignment-tracking.effect.spec.ts
projects/core/src/user/store/effects/consignment-tracking.effect.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/consignment-tracking.ts

feat: consignment tracking request fix and e2e test (GH-6149)

---

projects/core/src/product/services/product-loading.service.ts

fix: Improve caching for multiple scopes

---

projects/storefrontlib/src/cms-components/product/product-variants/guards/product-variant.guard.spec.ts
projects/storefrontlib/src/cms-components/product/product-variants/guards/product-variant.guard.ts

feature/GH-6214: allow smartedit to access pdp

---

projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-consigned-entries/order-consigned-entries.component.html
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-consigned-entries/order-consigned-entries.component.spec.ts
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-consigned-entries/order-consigned-entries.component.ts
projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-detail-items/order-detail-items.component.html

GH-6428: Add the applied promotions to the consigned entries

---

projects/storefrontapp-e2e-cypress/cypress/integration/mobile/coupon/coupon.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/coupon/coupon.e2e-spec.ts

fix: coupon code imports

---

projects/core/src/asm/store/selectors/asm-group.selectors.ts

fix: wrong import csagent-token.selectors.js

---

projects/core/src/cart/facade/selective-cart.service.spec.ts
projects/core/src/cart/facade/selective-cart.service.ts

fix: Fix selective cart multi store issue #6213

---

projects/core/src/occ/adapters/user/default-occ-user-config.ts
projects/core/src/occ/adapters/user/occ-user-order.adapter.spec.ts
projects/core/src/occ/adapters/user/occ-user-order.adapter.ts
projects/core/src/user/connectors/order/user-order.adapter.ts
projects/core/src/user/connectors/order/user-order.connector.spec.ts
projects/core/src/user/connectors/order/user-order.connector.ts
projects/core/src/user/facade/user-order.service.spec.ts
projects/core/src/user/facade/user-order.service.ts
projects/core/src/user/store/actions/consignment-tracking.action.spec.ts
projects/core/src/user/store/actions/consignment-tracking.action.ts
projects/core/src/user/store/effects/consignment-tracking.effect.spec.ts
projects/core/src/user/store/effects/consignment-tracking.effect.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/consignment-tracking.ts

fix: consignment tracking endpoint change

---

projects/storefrontlib/src/cms-components/product/product-tabs/product-reviews/product-reviews.component.html
projects/storefrontlib/src/cms-components/product/product-tabs/product-reviews/product-reviews.component.spec.ts
projects/storefrontlib/src/cms-components/product/product-tabs/product-reviews/product-reviews.component.ts

fix: Remove Breaking Changes for #4962

---

projects/storefrontlib/src/layout/a11y/focus-trap/directive/focus-trap.directive.ts
projects/storefrontlib/src/layout/a11y/focus-trap/focus-trap.module.ts
projects/storefrontlib/src/layout/a11y/focus-trap/index.ts
projects/storefrontlib/src/layout/a11y/focus-trap/service/focus-trap.service.ts
projects/storefrontlib/src/layout/a11y/index.ts

feat: Create focus-trap directive

---

projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.spec.ts
projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.ts

feat: Remove Breaking Changes for #4687

---

projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.html
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.ts

feat: Remove Breaking Changes for #4579

---

projects/core/src/occ/adapters/user/occ-user-order.adapter.spec.ts
projects/core/src/occ/adapters/user/occ-user-order.adapter.ts
projects/core/src/user/connectors/order/user-order.adapter.ts
projects/core/src/user/connectors/order/user-order.connector.spec.ts
projects/core/src/user/connectors/order/user-order.connector.ts
projects/core/src/user/store/actions/consignment-tracking.action.ts
projects/core/src/user/store/effects/consignment-tracking.effect.ts

fix: Revert breaking changes in consignment tracking

---

projects/storefrontapp-e2e-cypress/cypress/helpers/product-search.ts

chore: GH-6496 change camera results for product-search tests

---

projects/storefrontlib/src/cms-components/navigation/search-box/search-box.component.html
projects/storefrontlib/src/cms-components/navigation/search-box/search-box.component.spec.ts
projects/storefrontlib/src/cms-components/navigation/search-box/search-box.component.ts

feat: Breaking Changes for #3827

---

projects/storefrontlib/src/cms-components/navigation/navigation/navigation.service.spec.ts
projects/storefrontlib/src/cms-components/navigation/navigation/navigation.service.ts

feature/GH-5969: load missing navigation items when cms page updated

---

projects/storefrontlib/src/cms-components/product/product-variants/guards/product-variant.guard.spec.ts
projects/storefrontlib/src/cms-components/product/product-variants/guards/product-variant.guard.ts

Remove redundant check for smartedit

---

projects/storefrontapp-e2e-cypress/cypress/helpers/product-details.ts

feature/GH-6464: fix product details e2e test failing

---

projects/storefrontlib/src/cms-components/product/product-variants/guards/product-variant.guard.spec.ts
projects/storefrontlib/src/cms-components/product/product-variants/guards/product-variant.guard.ts

fix: add smartedit check to variant guard (#6502)

---

projects/storefrontlib/src/cms-components/product/product-variants/guards/product-variant.guard.spec.ts
projects/storefrontlib/src/cms-components/product/product-variants/guards/product-variant.guard.ts

remove redundant check (#6571)

---

projects/core/src/occ/adapters/user/default-occ-user-config.ts
projects/core/src/occ/adapters/user/occ-user-order.adapter.spec.ts
projects/core/src/occ/adapters/user/occ-user-order.adapter.ts
projects/core/src/user/connectors/order/user-order.adapter.ts
projects/core/src/user/connectors/order/user-order.connector.spec.ts
projects/core/src/user/connectors/order/user-order.connector.ts
projects/core/src/user/facade/user-order.service.spec.ts
projects/core/src/user/facade/user-order.service.ts
projects/core/src/user/store/actions/consignment-tracking.action.spec.ts
projects/core/src/user/store/actions/consignment-tracking.action.ts
projects/core/src/user/store/effects/consignment-tracking.effect.spec.ts
projects/core/src/user/store/effects/consignment-tracking.effect.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/consignment-tracking.ts

test: consignment tracking request failure and e2e test failing (GH-6149) - maintenance branch

---

projects/core/src/checkout/store/effects/checkout.effect.spec.ts
projects/core/src/checkout/store/effects/checkout.effect.ts

feature/GH-6569: fix the checkout bug when change language

---

projects/storefrontapp-e2e-cypress/cypress/helpers/cart.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/cart.e2e-spec.ts

test: Improve stability of merge cart e2e spec

---

projects/storefrontapp-e2e-cypress/cypress/helpers/cart.ts
projects/storefrontapp-e2e-cypress/cypress/integration/regression/cart.e2e-spec.ts

test: Improve stability of merge cart e2e spec (#6627)

---

projects/schematics/README.md

chore: update schematics docs

---

projects/storefrontapp-e2e-cypress/cypress/helpers/cart.ts
projects/storefrontapp-e2e-cypress/cypress/integration/mobile/cart-mobile.e2e-spec.ts

test: Add missing route in cart mobile e2e

---

projects/storefrontapp-e2e-cypress/cypress/helpers/cart.ts
projects/storefrontapp-e2e-cypress/cypress/integration/mobile/cart-mobile.e2e-spec.ts

test: Add missing route in cart mobile e2e (#6643)

---

projects/core/src/cart/facade/selective-cart.service.spec.ts
projects/core/src/cart/facade/selective-cart.service.ts

Commit the fix for selective cart multi store issue into release 1.5.x branch

---

projects/storefrontapp-e2e-cypress/cypress.ci.json
projects/storefrontapp-e2e-cypress/cypress.json
projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts

GH-6145: Add wait before order history check.

---

projects/core/src/global-message/http-interceptors/handlers/bad-request.handler.ts

fix: hide "object no longer valid" message temporarily

---

projects/storefrontapp-e2e-cypress/cypress/helpers/save-for-later.ts

GH-6463: Adjust save-for-later e2e tests for dev17

---

projects/storefrontapp-e2e-cypress/cypress/helpers/my-coupons.ts

fix: adjust asserts checks for e2e

---

projects/storefrontapp-e2e-cypress/cypress/helpers/save-for-later.ts

fix: Adjust save-for-later e2e tests for dev17 (#6463)

---

projects/storefrontapp-cds-integration/src/environments/environment.ci.ts
projects/storefrontapp-cds-integration/src/environments/environment.ts
projects/storefrontapp-e2e-cypress/cypress.ci.json
projects/storefrontapp-e2e-cypress/cypress.json
projects/storefrontapp-e2e-cypress/cypress/helpers/product-search.ts
projects/storefrontapp/src/environments/environment.ci.ts

GH-6649: Use 1905.11 for the 1.5 release.

---

projects/storefrontapp-cds-integration/src/environments/environment.ci.ts
projects/storefrontapp-cds-integration/src/environments/environment.ts
projects/storefrontapp-e2e-cypress/cypress.ci.json
projects/storefrontapp-e2e-cypress/cypress.json
projects/storefrontapp-e2e-cypress/cypress/helpers/product-search.ts
projects/storefrontapp/src/environments/environment.ci.ts

ci: Point the CI to dev17-1905.11 (GH-6649)

---

projects/storefrontapp-cds-integration/src/main.server.ts
projects/storefrontapp-cds-integration/src/polyfills.ts
projects/storefrontapp-e2e-cypress/cypress/integration/vendor/cds/merchandising-carousel.e2e-spec.ts
projects/storefrontapp-e2e-cypress/cypress/integration/vendor/cds/profile-tag.e2e-spec.ts
projects/storefrontapp/src/main.server.ts

cds application does not start due to missing dependencies for `localize/init`

chore: added missing imports for cds application to start it + e2e price fix

---

projects/storefrontlib/src/cms-components/product/product-tabs/product-reviews/product-reviews.component.ts

feat: Remove breaking change deprs for product page tabs

---

projects/storefrontlib/src/cms-components/user/register/register.component.html
projects/storefrontlib/src/cms-components/user/register/register.component.spec.ts
projects/storefrontlib/src/cms-components/user/register/register.component.ts

feat: Register button breaking change deps removal

---

projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-form/payment-form.component.html
projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-form/payment-form.component.spec.ts
projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-form/payment-form.component.ts

feat: Remove payment-form breaking change deprecations

---

projects/storefrontapp-e2e-cypress/cypress/helpers/my-coupons.ts

fix: adjust asserts checks for e2e (#6700)

---

projects/storefrontlib/src/cms-components/user/login-form/login-form.component.html
projects/storefrontlib/src/cms-components/user/login-form/login-form.component.spec.ts
projects/storefrontlib/src/cms-components/user/login-form/login-form.component.ts

feat: Remove breaking change deprecations for login form

---

projects/assets/src/translations/en/organization.ts
projects/assets/src/translations/translation-chunks-config.ts
projects/core/src/model/budget.model.ts
projects/core/src/organization/facade/cost-center.service.ts
projects/core/src/organization/store/actions/cost-center.action.spec.ts
projects/core/src/organization/store/actions/cost-center.action.ts
projects/core/src/organization/store/effects/cost-center.effect.spec.ts
projects/core/src/organization/store/effects/cost-center.effect.ts
projects/core/src/organization/store/reducers/budget.reducer.ts
projects/core/src/organization/store/reducers/cost-center.reducer.ts
projects/core/src/organization/store/reducers/index.ts
projects/core/src/organization/store/reducers/org-unit.reducer.ts
projects/core/src/organization/store/reducers/permission.reducer.ts
projects/storefrontlib/src/cms-components/cms-lib.module.ts
projects/storefrontlib/src/cms-components/organization/budgets/budget-list/budget-list.component.ts
projects/storefrontlib/src/cms-components/organization/cost-centers/cost-center-assign-budgets/cost-center-assign-budgets.component.html
projects/storefrontlib/src/cms-components/organization/cost-centers/cost-center-assign-budgets/cost-center-assign-budgets.component.spec.ts
projects/storefrontlib/src/cms-components/organization/cost-centers/cost-center-assign-budgets/cost-center-assign-budgets.component.ts
projects/storefrontlib/src/cms-components/organization/cost-centers/cost-center-assign-budgets/cost-center-assign-budgets.module.ts
projects/storefrontlib/src/cms-components/organization/cost-centers/cost-center-details/cost-center-details.component.html
projects/storefrontlib/src/cms-components/organization/cost-centers/cost-center-details/cost-center-details.component.ts
projects/storefrontlib/src/cms-components/organization/cost-centers/cost-center-list/cost-center-list.component.ts
projects/storefrontlib/src/cms-components/organization/cost-centers/index.ts
projects/storefrontlib/src/cms-components/organization/permissions/permission-list/permission-list.component.ts
projects/storefrontlib/src/cms-structure/routing/default-routing-config.ts
projects/storefrontlib/src/shared/components/table/table.component.html
projects/storefrontlib/src/shared/components/table/table.component.ts

feat: Update Cost center details view with list of budgets and possibility to manage #6543

---

projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.html
projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.ts

fix: close nav category on esc key

---

.gitignore
projects/assets/package.json
projects/cds/.release-it.json
projects/core/.release-it.json

chore: release 2.0.0-next.0

---

projects/storefrontlib/src/cms-components/organization/abstract-component/abstract-form.component.ts
projects/storefrontlib/src/cms-components/organization/budgets/budget-create/budget-create.component.html
projects/storefrontlib/src/cms-components/organization/budgets/budget-edit/budget-edit.component.html
projects/storefrontlib/src/cms-components/organization/budgets/budget-form/budget-form.component.html
projects/storefrontlib/src/cms-components/organization/budgets/budget-form/budget-form.component.ts
projects/storefrontlib/src/cms-components/organization/cost-centers/cost-center-create/cost-center-create.component.html
projects/storefrontlib/src/cms-components/organization/cost-centers/cost-center-edit/cost-center-edit.component.html
projects/storefrontlib/src/cms-components/organization/cost-centers/cost-center-form/cost-center-form.component.html
projects/storefrontlib/src/cms-components/organization/cost-centers/cost-center-form/cost-center-form.component.ts
projects/storefrontlib/src/cms-components/organization/permissions/permission-create/permission-create.component.html
projects/storefrontlib/src/cms-components/organization/permissions/permission-edit/permission-edit.component.html
projects/storefrontlib/src/cms-components/organization/permissions/permission-form/permission-form.component.html
projects/storefrontlib/src/cms-components/organization/permissions/permission-form/permission-form.component.ts

Add form abstract component #6755

---

projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order.config.ts
projects/storefrontapp-e2e-cypress/cypress/helpers/accessibility/tabbing-order/save-for-later.ts
projects/storefrontapp-e2e-cypress/cypress/integration/accessibility/tabbing-order.e2e-spec.ts
projects/storefrontlib/src/cms-components/cart/cart-details/cart-details.component.html
projects/storefrontlib/src/cms-components/cart/save-for-later/save-for-later.component.html

feat: GH-6444, add a11y for save for later.

---

projects/storefrontlib/src/cms-components/organization/budgets/budget-details/budget-details.component.html
projects/storefrontlib/src/cms-components/organization/cost-centers/cost-center-details/cost-center-details.component.html
projects/storefrontlib/src/cms-components/organization/permissions/permission-details/permission-details.component.html
projects/storefrontlib/src/cms-components/organization/units/unit-details/unit-details.component.html
projects/storefrontstyles/scss/components/organization/_index.scss
projects/storefrontstyles/scss/components/organization/_organization-details.scss
projects/storefrontstyles/scss/components/organization/_organization-form.scss
projects/storefrontstyles/scss/components/organization/budgets/_budget-details.scss
projects/storefrontstyles/scss/components/organization/cost-centers/_cost-center-details.scss
projects/storefrontstyles/scss/components/organization/permissions/_permission-details.scss
projects/storefrontstyles/scss/components/organization/units/_unit-details.scss

fix: Wrapping text in the details page #6459
