- projects/storefrontlib/src/lib/cart/components/add-to-cart/added-to-cart-dialog/added-to-cart-dialog.component.html
- projects/storefrontlib/src/lib/cart/components/add-to-cart/added-to-cart-dialog/added-to-cart-dialog.component.spec.ts
- projects/storefrontlib/src/lib/cart/components/add-to-cart/added-to-cart-dialog/added-to-cart-dialog.component.ts
After we load dialog content we move focus to the element with ngbAutoFocus attribute. I decided not to change styles for focused close button, because that should be first consulted from UX/Design perspective.
Closes #209
> GH-209: Better focus managment in dialog after loaded

- projects/storefrontlib/src/lib/ui/pages/product-page/product-page.component.html
- projects/storefrontlib/src/lib/ui/pages/product-page/product-page.component.spec.ts
Previously the container component subscibed to router state and passed `productCode` route param down the component tree. One of the child components was talking with OCC endpoint on every `productCode` change.
When leaving the product details page, router state already changed to `/cart`. But Product details page was still active for one change detection cycle. This caused passing down the components tree the undefined `productCode` route param.
Child components wrapped in `*ngIf="productCode"`
Closes #718
> GH-718 avoid unnecessary call to OCC when leaving product details page

- docs/archive/1808/contributorsetup.md
- docs/archive/1808/setupandinstallation.md
- docs/back_end_installation/1808/back_end_installation.md
- docs/back_end_installation/1811/back_end_installation.md
- docs/contributorsetup.md
- docs/setupandinstallation.md
Need to fix a bunch of broken links in
* setupandinstallation.md
* contributorsetup.md
* 1808/back_end_installation.md
* 1811/back_end_installation.md
* archive/1808/setupandinstallation.md
* archive/1808/contributorsetup.md
> GH-979: Fixing broken links in various install docs

- projects/storefrontlib/src/lib/cms/page-layout/page-layout.component.html
- projects/storefrontlib/src/lib/cms/page-layout/page-layout.module.ts
When page layouts are rendered we add an outlet for either the section or page template. This allows to customise (replace, or append) a page template or a section (i.e. header)
closes #989
> feat(@spartacus/storefront): add outlets to page layouts

- projects/core/src/routing/configurable-routes/url-translation/url-translation.service.spec.ts
- projects/core/src/routing/configurable-routes/url-translation/url-translation.service.ts
Previously, when empty string came from CMS data as an URL (for example to home page), then it couldn't be translated due to validation which was rejecting empty string. Now validation allows empty string.
Additionaly, the typo in unit tests was fixed (line 170).
fixes GH-985
> fix(@spartacus/core): accept empty string URL to be recognized and translated

- CONTRIBUTING.md
Links to the commit guidelines and development tools docs were broken. These are now fixed.
> GH-856: Fix broken links in CONTRIBUTING.md

- projects/storefrontlib/src/lib/occ/docs/cms-component-implementation.md
docs for GH-925
By the way, I fixed the outdated `cmsComponentMapping` --> `cmsMapping`
> docs(@spartacus/storefrontlib): support disabling CMS components in SSR

- projects/storefrontapp-e2e-cypress/cypress/integration/big-happy-path.e2e-spec.ts
- projects/storefrontapp-e2e-cypress/cypress/integration/homepage.e2e-spec.ts
Changed a few things in homepage test to align with cypress good practices.
Also renamed files to use the same naming convention with `e2e-spec.ts` extension.
Closes #1308
> test: Improve homepage test and use same naming convention

- docs/architecture/seo.md
- projects/core/src/cms/model/page.model.ts
- projects/core/src/cms/page/page.resolvers.ts
- projects/core/src/product/services/product-page-meta.resolver.spec.ts
- projects/core/src/product/services/product-page-meta.resolver.ts
- projects/storefrontlib/src/lib/cms-lib/breadcrumb/breadcrumb.component.ts
The page title for the SERP is not necessary the same as the page heading shown in the UI. This PR provides a dedicated page heading resolver to differentiate the two.
closes #1528
> feat(@spartacus/storefront): allow for different page heading and titles in meta resolvers

- docs/architecture/seo.md
- docs/setupandinstallation.md
- projects/storefrontlib/src/lib/occ/docs/cms-component-implementation.md
Fixed typos or made minor improvements in the following files:
- `setupandinstall.md'
- `seo.md`
- `cms-component-implementation.md`
> GH-1453: Fix various typos

- projects/core/src/cms/store/effects/page.effect.spec.ts
- projects/core/src/cms/store/effects/page.effect.ts
- projects/storefrontlib/src/cms-structure/page/component/component-wrapper.directive.spec.ts
- projects/storefrontlib/src/cms-structure/page/component/component-wrapper.directive.ts
- projects/storefrontlib/src/cms-structure/page/slot/page-slot.component.html
- projects/storefrontlib/src/cms-structure/page/slot/page-slot.component.spec.ts
- projects/storefrontlib/src/cms-structure/page/slot/page-slot.component.ts
The logical type for components is mainly driven by the component `typeCode`, however in case of a `FlexComponent` (or `JspIncludeComponent`), the logical type is dictated by an attribute. The logic to extract the attribute will be populated in an effect, to not bother the UI implementation.
closes #1681
> feat(core): move flexType mapping logic to effects

- projects/storefrontlib/src/lib/checkout/guards/checkout.guard.spec.ts
- projects/storefrontlib/src/lib/checkout/guards/checkout.guard.ts
- projects/storefrontlib/src/lib/checkout/guards/index.ts
- projects/storefrontlib/src/lib/ui/pages/pages.module.ts
Added checkout guard with `?forced=true` param passed (with unit tests). As for now additional check for cart/user hasn't been introduced (blocked by #1179, RAY-229). Doing this PR so #1387 can be started.
closes GH-1182
> feat: add checkout guard (GH-1182)

- projects/core/src/site-context/services/site-context-routes-handler.spec.ts
- projects/core/src/site-context/services/site-context-routes-handler.ts
Makes possible to use site context parameters from URL (like baseSite), before first routing event is dispatched.
Closes GH-1819
> fix: Get site config from route on init

- projects/core/src/cms/config/cms-config.ts
- projects/storefrontlib/src/lib/cms/guards/cms-page.guard.spec.ts
- projects/storefrontlib/src/lib/cms/guards/cms-page.guard.ts
- projects/storefrontlib/src/lib/cms/services/cms-guards.service.spec.ts
- projects/storefrontlib/src/lib/cms/services/cms-guards.service.ts
- projects/storefrontlib/src/lib/cms/services/cms-mapping.service.spec.ts
- projects/storefrontlib/src/lib/cms/services/cms-mapping.service.ts
Some pages require authentication. Authentication can be page driven, but it's actually based on components used on the pages; components that require authorised users can moved by users from page to page.
For the CMS we've suggested to return a 403, but for non-cms use-cases (and for as long as the cms doesn't provide auth per page), we like to use a setting per component type, that instructs the UI to redirect to the login page in case there's no authenticated user.
The component guard instructions must be evaluated during page load, and in case any guarded component is part of the page, the user must be redirected.
The login page is currently a hard-coded route.
The component guard configuration can be part of the component mapping configuration.
Closes GH-1678
> feat: Component guarding

- projects/core/src/i18n/config/i18n-config.ts
- projects/core/src/i18n/i18next/i18next-translation.service.spec.ts
- projects/core/src/i18n/i18next/i18next-translation.service.ts
Currenlty, keys defined in the html templates contain the name of the file with lazy loaded chunk (we call it namespace). It couples tightly the html templates with the structure of lazy loaded chunks of translations. This may lead into problems when a customer wants to rearrange chunks (i.e. merge translations related to two features into one chunk).
So we will use keys without namespaces in the templates and we will map them to namespaces by config.
fixes GH-1894
> feat(core): config mapping from key to name of lazy loaded translation chunk

- projects/core/src/cms/services/component-mapper.service.ts
Currently we have a warning in the console, when the CMS component doens't have a mapping in the configuration.
But there may be a case when the mapping is provided, but the developer forgot to add the component reference into `entryComponent` array. Then the component doesn't show up and there is no hint what went wrong.
fixes GH-1897
> fix(storefront): warn when CMS component not added to entry components

- projects/core/src/product/services/product-page-meta.resolver.spec.ts
- projects/core/src/product/services/product-page-meta.resolver.ts
To improve SEO (especially the title on the SERP), the category name is resolved as part of the page title. The format looks like: **Product name | category name | manufacturer**
A specific page title can be added by providing a custom `ProductPageMetaResolver`.
closes #2003
> feat(core): add category name to page title resolver

- projects/core/src/checkout/services/checkout-page-meta.resolver.ts
- projects/core/src/cms/page/content-page-meta.resolver.ts
- projects/core/src/cms/page/page.resolvers.ts
- projects/core/src/product/services/category-page-meta.resolver.ts
- projects/core/src/product/services/product-page-meta.resolver.ts
- projects/core/src/product/services/search-page-meta.resolver.ts
The interfaces for extension points of `PageMetaResolver`s now have `Observable<string>` signature. This allows for async translations of i.e. page title.
fixes GH-2168
> refactor(core) : change interfaces of page meta resolvers to observable

- projects/storefrontlib/src/cms-components/myaccount/update-profile/components/update-profile-form.component.html
Fix a typo which causes not translated label at profile update view.
> fix: typo in update profile

- projects/core/src/i18n/date.pipe.spec.ts
- projects/core/src/i18n/date.pipe.ts
- projects/core/src/i18n/i18n.module.ts
- projects/core/src/i18n/testing/mock-date.pipe.ts
The backward compatibility compiler of Angular Ivy had problem with our `DatePipe` type, probably due to the conflict with Angular's native `DatePipe`. So as a workaround, we rename the type to `CxDatePipe`.
close GH-2344
> refactor: rename type DatePipe to CxDatePipe

- projects/core/src/model/misc.model.ts
- projects/core/src/model/unused.model.ts
- projects/core/src/occ/adapters/user/occ-user-account.adapter.ts
- projects/core/src/user/connectors/account/converters.ts
- projects/core/src/user/connectors/account/user-account.adapter.ts
- projects/core/src/user/connectors/account/user-account.connector.spec.ts
- projects/core/src/user/connectors/account/user-account.connector.ts
- projects/core/src/user/facade/user.service.spec.ts
- projects/core/src/user/facade/user.service.ts
- projects/core/src/user/index.ts
- projects/core/src/user/model/user.model.ts
- projects/core/src/user/store/actions/user-register.action.spec.ts
- projects/core/src/user/store/actions/user-register.action.ts
- projects/core/src/user/store/effects/user-register.effect.spec.ts
- projects/core/src/user/store/effects/user-register.effect.ts
- projects/storefrontapp-e2e-cypress/cypress.json
- projects/storefrontapp/src/environments/environment.ci.ts
- projects/storefrontlib/src/cms-components/user/register/register.component.ts
n the register user form we use our custom interface UserRegisterFormData, but we have a standard interface UserSignUp with the same fields already in place (currently in file unused.model.ts). We should remove custom model and reuse the standard one (which can be moved to user.model.ts.
> Reuse existing type UserSignUp

- projects/storefrontlib/src/cms-components/product/product-list/container/product-list.component.ts
> fix: Selected filters on search result page reset after selecting a page form the pagination

- CONTRIBUTING.md
- README.md
Update links in Readme.md and Contributing.md to point to new GitHub Pages documentation site.
> GH-3046: Update links to point to GH Pages site

- projects/storefrontlib/src/shared/components/media/media.service.spec.ts
- projects/storefrontlib/src/shared/components/media/media.service.ts
> fix(storefront): fix null pointer when a media container does not have a URL property

- projects/storefrontlib/src/cms-structure/services/index.ts
> Exclude internal cms routing services from public API

- projects/core/public_api.ts
- projects/core/src/cx-api/cx-api.module.ts
- projects/core/src/cx-api/index.ts
- projects/storefrontlib/src/cms-structure/page/component/component-wrapper.directive.spec.ts
- projects/storefrontlib/src/cms-structure/page/component/component-wrapper.directive.ts
- projects/storefrontlib/src/cms-structure/page/component/cx-api.service.spec.ts
- projects/storefrontlib/src/cms-structure/page/component/cx-api.service.ts
cxApi service is used to provide api to cms web components implementation, which is experimental at the moment, and should not be exposed as a general usage service.
Closes GH-3425
> Remove cxApi service from public api

- projects/core/src/cart/store/actions/cart.action.spec.ts
- projects/core/src/cart/store/actions/cart.action.ts
- projects/core/src/cart/store/effects/cart.effect.spec.ts
- projects/core/src/cart/store/effects/cart.effect.ts
- projects/core/src/cart/store/reducers/cart.reducer.spec.ts
- projects/core/src/cart/store/reducers/cart.reducer.ts
- projects/storefrontapp-e2e-cypress/cypress/integration/regression/reset-password/reset-password.e2e-spec.ts
Error "Cart not found" will still be displayed. It will be shown once.
Apart from the fix for infinite loop and wrote some unit tests for code that wasn't cover by existing tests.
Extra PR for this issue will include some UX improvement for handling cart between devices but introduces breaking changes.
The behavior of cart in this PR:
- create cart on one device
- login on another device to the same account (you get the same cart as on another device)
Another use case, where you end up with separate carts on each device:
- complete order on one device (cart no longer exists)
- login on another device
- add something to cart on each device
- on each device, you have a different cart
Closes #3478
> fix: Prevent infinite loop on cart not found error

- projects/core/src/auth/store/auth-store.module.ts
- projects/core/src/kyma/store/kyma-store.module.ts
- projects/core/src/state/config/default-state-config.ts
- projects/core/src/state/config/state-config.ts
- projects/core/src/state/reducers/storage-sync.reducer.spec.ts
- projects/core/src/state/reducers/storage-sync.reducer.ts
- projects/core/src/state/reducers/transfer-state.reducer.ts
- projects/core/src/state/utils/get-state-slice.spec.ts
- projects/core/src/state/utils/get-state-slice.ts
Reverted 2 commits that touched this feature:
https://github.com/SAP/cloud-commerce-spartacus-storefront/commit/8e89ffedc9fb7efdb7e2ada59151dba91815757f
https://github.com/SAP/cloud-commerce-spartacus-storefront/commit/d15e792e12225670a1a4cda58b2b18c174bde28b
PRs that can be reopened and introduced to next beta:
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3560
https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3662
For kyma I didn't noticed refresh_token returned from auth server and I am not sure if we need that exclusion mechanism.
Closes #3998
> Revert commits with exclusion mechanism for syncing with browser storage

- projects/storefrontlib/src/cms-structure/guards/cms-page.guard.ts
Fix bug causing that could cause double cms page logic execution in case of long-running guards.
Closes GH-4150
> Fix cms page logic execution

- projects/assets/.release-it.changelog.json
- projects/assets/.release-it.json
- projects/core/.release-it.changelog.json
- projects/core/.release-it.json
- projects/storefrontlib/.release-it.changelog.json
- projects/storefrontlib/.release-it.json
- projects/storefrontstyles/.release-it.changelog.json
- projects/storefrontstyles/.release-it.json
For schematics release, `release-it` was updated.
Also fixed configs to match the new version and remove not needed parts after change in our git-flow.
> chore: Update release-it configs

- projects/core/src/auth/guards/auth-redirect.service.ts
- projects/core/src/auth/guards/auth.guard.ts
- projects/core/src/routing/configurable-routes/config/routing-config.ts
- projects/core/src/routing/configurable-routes/routes-config.ts
- projects/core/src/routing/index.ts
- projects/core/src/routing/protected-routes/index.ts
- projects/core/src/routing/protected-routes/protected-routes.guard.spec.ts
- projects/core/src/routing/protected-routes/protected-routes.guard.ts
- projects/core/src/routing/protected-routes/protected-routes.service.spec.ts
- projects/core/src/routing/protected-routes/protected-routes.service.ts
- projects/storefrontlib/src/cms-structure/guards/cms-page.guard.spec.ts
- projects/storefrontlib/src/cms-structure/guards/cms-page.guard.ts
- projects/storefrontlib/src/cms-structure/routing/default-routing-config.ts
A lot of B2B storefronts need a closed store, which you cannot enter without logging in. There will be typically at least one page (login) public, or a few (such as register, help, support, etc.).
In order to achieve this now we configure in our libraries the Login related pages (login, register, forget password) as a public routes, In order to enable/disable the closed storefront we introduce one configuration to close the storefront.
By the way:
- fixed a bug: After login you should be redirected back to the anticipated protected page (not the last openend page). 
- marked as `protected` a few dependencies in the constructor of `CmsPageGuard` - only those exposed in our Public API
close GH-4594
> feat: closed storefront

- scripts/versions.ts
Release note script wasn't working correctly. `npm-package-versions` is a common js module and standard import didn't worked correctly with default export.
> chore: Fix import in release notes generation script

- projects/core/src/occ/services/occ-endpoints.service.spec.ts
- projects/core/src/occ/services/occ-endpoints.service.ts
> fix: escape special characters for url params in url generation

- projects/storefrontapp-e2e-cypress/cypress/tsconfig.json
- tsconfig.json
Assertion type was set to use Chai everywhere (even in karma/jasmine) tests.
Fixed `tsconfig` files to correctly match this type in different spec files.
> chore: Fix tsconfig to match Assertion types

- projects/storefrontlib/package.json
> fix: Add ngx-infinite-scroll to list of peer dependencies (GH-4857)

- tsconfig.json
It gives much more control in terms of shaping our public API. Now with `\** @internal *\` comment, you can mark method/class to be visible as public only in the library itself. The method is not available in public API.
🚨  **Warning**: don't use on constructor!
To test:
- mark public method that is used only in the same lib eg. `AuthService.getOccUserId`
- check if you can use it in other files in the same lib
- check if it is hidden in public API (try to import in `app.module.ts`)
Closes #5209
> chore: Enable @internal docs for methods/classes

- projects/core/src/cart/facade/cart-voucher.service.ts
- projects/storefrontlib/src/cms-components/cart/cart-coupon/cart-coupon.component.spec.ts
- projects/storefrontlib/src/cms-components/cart/cart-coupon/cart-coupon.component.ts
Improve the logic to get cartId which should be cart.guid when anonymous applying coupon in cart page
Breaking Changes:
Unit tests of cart-voucher.service and cart-coupon.component
Closed #5189
> Fix: Apply coupon to anonymous cart returns Cart not found (GH-5189)

- projects/storefrontstyles/_index.scss
- projects/storefrontstyles/scss/_page-template.scss
- projects/storefrontstyles/scss/_sparta-theme.scss
- projects/storefrontstyles/scss/cxbase/_mixins.scss
- projects/storefrontstyles/scss/cxbase/_variables.scss
- projects/storefrontstyles/scss/layout/_index.scss
- projects/storefrontstyles/scss/layout/page-templates/_common-template.scss
- projects/storefrontstyles/scss/layout/page-templates/_order-detail-page.scss
- projects/storefrontstyles/scss/layout/page-templates/_product-detail.scss
- projects/storefrontstyles/scss/theme/sparta/_variables.scss
Similar to the theming we use for components (i.e. calydon), we can now use a theme for a page layouts. The page layout can have addition placeholder selectors, so that whenever the theme is used, additional styles rules are added to the final CSS. 
Additional, we introduced a white and blacklist of page templates so that customers can more easily opt-out of certain page template styles. The variables are `$page-template-blacklist` and `$page-template-whitelist`. 
Moreover, the page templates can now be imported separately, using `@import '@spartacus/styles/scss/page-template';`
closes #5159
> feat (styles): introduce theme driven page templates

- projects/storefrontlib/src/cms-structure/outlet/outlet.directive.ts
- projects/storefrontlib/src/cms-structure/outlet/outlet.service.spec.ts
- projects/storefrontlib/src/cms-structure/outlet/outlet.service.ts
Similar to the dynamic creation of CMS components, you can add components instantly to an outlet position. 
closes #5355
> Add components dynamically to outlets

- projects/storefrontlib/src/layout/main/main.module.ts
- projects/storefrontlib/src/layout/main/storefront.component.html
With this PR you can change the UI of the overall storefront, header and footer by adding an `ng-template` for these outlet references:
- `cx-storefront`
- `cx-header`
- `cx-footer`
You can use these outlet references to create additional UI :
```html
<ng-template cxOutletRef="cx-header" cxOutletPos="after">
Custom UI for the header
</ng-template>
```
closes #5357
> Introduce cx-storefront, cx-header and cx-footer outlet

- projects/core/src/occ/config-loader/index.ts
OccConfigLoaderService
OccSitesConfigLoader
closes GH-5570
> fix: missing exports of services for site auto-config (for 1.3.1)

- projects/core/src/occ/adapters/checkout/occ-checkout.adapter.ts
The thing that prevented going to the second step of the checkout was failed requests for checkout details. There wasn't any retry mechanism and once it failed component kept waiting for checkout data, but it was never fetched.
This is a quick fix. Better queuing for cart requests should be implemented to avoid `Jalo` errors and help with race conditions issues. For now, the retry mechanism is the easiest way to help with this issue.
Closes #5632
> fix: Retries for checkout details call

- projects/cds/src/merchandising/facade/cds-merchandising-user-context.service.spec.ts
- projects/cds/src/merchandising/facade/cds-merchandising-user-context.service.ts
If a `brandCode` is present, use that as the category when making requests to the strategy service from a merchandising carousel.
This is to work around the fact that when visiting a brand page the `categoryCode` is not populated
> COL-212 Use brandCode as category in merchandising carousel

- projects/core/src/cart/store/effects/cart.effect.spec.ts
- projects/core/src/cart/store/effects/cart.effect.ts
We can't detect if we modify the active cart in `cart.reducer`.
To fix the updates we need to prevent the only 2 actions that can change it's content if we operate on cart different than the active.
Closes #5792
> fix: Update old cart store only for load/create on active cart

- projects/core/src/cms/facade/cms.service.ts
- projects/core/src/cms/store/effects/component.effect.spec.ts
- projects/core/src/cms/store/effects/component.effect.ts
Closes #5845
Coalesce multiple calls for a component data into one.
Should make #3769 obsolete, as optimization is done under the hood.
> feat: Optimize CMS components data loading

- projects/core/src/cms/store/effects/component.effect.spec.ts
- projects/core/src/cms/store/effects/component.effect.ts
Fallback to CmsConnector.get for pre 1.4 versions as before, in case customers relied on customizations around this.
Closes #5876
> fix: Backward compatibility fix for cms componend data loading

- README.md
License link had .txt in the link but there is no extension
> fix link to license file from readme

- projects/storefrontlib/src/cms-structure/seo/structured-data/json-ld-script.factory.spec.ts
- projects/storefrontlib/src/cms-structure/seo/structured-data/json-ld-script.factory.ts
- projects/storefrontlib/src/cms-structure/seo/structured-data/json-ld.directive.spec.ts
- projects/storefrontlib/src/cms-structure/seo/structured-data/json-ld.directive.ts
We're leveraging standard angular sanitiser during the creation of json-ld.
closes #5636
> fix: add sanitiser to json-ld script content

- scripts/changelog.ts
Correctly find mentioned issues in release notes script when they are prefixed with `GH-` or `gh-` and `#` in commit messages. 
Done according to: https://github.com/conventional-changelog-archived-repos/conventional-commits-parser#issueprefixes
QA steps:
- create some file in core library
- commit it with message ending with `Closes GH-123`. Commit must start with `fix` or `feat` prefix to be picked.
- run release-notes script and check if this commit is picked in notes `npm run release-notes:core -- --to core-1.5.0 > core.md`
- this commit should correctly link to issue `123`
Previously only `#` worked.
> chore: Catch issues references with `GH-` and `gh-` prefix

- projects/storefrontlib/src/cms-components/navigation/navigation/navigation-ui.component.html
- projects/storefrontstyles/scss/components/content/navigation/_navigation-ui.scss
Visual space around navigation links is now part of the link.
This is introduced with `calydon` theme during the 1.x release. 
closes #5928 
closes #5667
> fix: only navigable items used the pointer cursor

- projects/core/src/user/store/effects/user-orders.effect.spec.ts
- projects/core/src/user/store/effects/user-orders.effect.ts
> fix: Clear user orders on language change action (#5919)

- projects/cds/src/profiletag/http-interceptors/consent-reference-interceptor.spec.ts
- projects/cds/src/profiletag/http-interceptors/consent-reference-interceptor.ts
- projects/cds/src/profiletag/http-interceptors/debug-interceptor.spec.ts
- projects/cds/src/profiletag/services/profiletag-event.service.spec.ts
- projects/cds/src/profiletag/services/profiletag-event.service.ts
Publicly exposes the consent-reference within the CDS module via a singleton method, allowing late subscribers to get the last issued consent-reference.
Closes GH-5941
> feat: change the profiletag consent-reference to be available within the CDS module (GH-5941)

- projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item/cart-item.component.html
- projects/storefrontlib/src/cms-components/wish-list/components/wish-list-item/wish-list-item.component.html
It is technically possible to have no `selected` in `baseOptions[0]`
> Added question mark

- projects/core/src/i18n/config/i18n-config.ts
- projects/core/src/i18n/i18next/i18next-init.spec.ts
- projects/core/src/i18n/i18next/i18next-init.ts
- projects/core/src/i18n/i18next/i18next-providers.ts
The `i18next-xhr-plugin` uses XHR to load translation files by default, which doesn't work in SSR. Now it's fixed by defining the function backend.ajax of i18next that uses Angular HttpClient under the hood, so it works in SSR.
Deprecated the Spartacus config option i18n.backend.crossDomain since it's not used anymore.
closes GH-6030
> fix: XMLHttpRequest error when dynamically loading translations using SSR (for 1.4.x)

- projects/storefrontlib/src/shared/components/item-counter/item-counter.component.html
- projects/storefrontlib/src/shared/components/item-counter/item-counter.component.spec.ts
- projects/storefrontlib/src/shared/components/item-counter/item-counter.component.ts
> fix: PdP qty should be reset to 1 if qty removed and clicked outside (GH-3150)

- projects/core/src/product/services/product-page-meta.resolver.ts
- projects/storefrontlib/src/cms-components/product/carousel/product-carousel/product-carousel.component.ts
- projects/storefrontlib/src/cms-components/product/current-product.service.ts
- projects/storefrontlib/src/cms-components/product/product-tabs/product-attributes/product-attributes.component.ts
1. Use `ProductScopes.ATTRIBUTES` in `ProductAttributesComponent` only when the feature level `1.4` (done inside the logic of the `CurrentProductService`).
2. Deprecated a few constructors which used optional argument - features config service
close GH-6167
> fix: avoid loading product classifications twice when feature level <1.4

- projects/core/src/product/services/product-page-meta.resolver.ts
- projects/storefrontlib/src/cms-components/product/carousel/product-carousel/product-carousel.component.ts
- projects/storefrontlib/src/cms-components/product/current-product.service.ts
1. Use `ProductScopes.ATTRIBUTES` in `ProductAttributesComponent` only when the feature level `1.4` (done inside the logic of the `CurrentProductService`).
2. Deprecated a few constructors which used optional argument - features config service
closes GH-6167
> fix: (1.4.x branch) avoid loading product classifications twice when feature level <1.4 

- projects/storefrontapp-e2e-cypress/cypress/helpers/asm.ts
- projects/storefrontapp-e2e-cypress/cypress/integration/mobile/checkout/checkout-flow-mobile.e2e-spec.ts
- projects/storefrontapp-e2e-cypress/cypress/integration/mobile/my-account/order-history-orders-flow-mobile.e2e-spec.ts
- projects/storefrontapp-e2e-cypress/cypress/integration/regression/checkout/checkout-as-guest.e2e-spec.ts
- projects/storefrontapp-e2e-cypress/cypress/integration/regression/my-account/order-history-orders-flow.e2e-spec.ts
- projects/storefrontapp-e2e-cypress/cypress/integration/regression/site-context/language/language-my-account-pages.e2e-spec.ts
- projects/storefrontapp-e2e-cypress/cypress/integration/smoke/checkout-flow.e2e-spec.ts
> GH-6218: Re-enable tests that depend on the order history.

- projects/storefrontlib/src/cms-structure/page/slot/page-slot.component.html
- projects/storefrontlib/src/cms-structure/page/slot/page-slot.component.spec.ts
- projects/storefrontlib/src/cms-structure/page/slot/page-slot.component.ts
In 1.4 we accidentally introduced a breaking change, it's a very edge case though. 
fixes #6318
> fix: Page Slot component overwrites classes (6318)

- projects/core/src/routing/services/url-matcher-factory.service.ts
- projects/core/src/util/glob-utils.ts
The PR https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/4250 contained some copies and modifications of Angular's code. Here we add missing MIT license noticies.
> chore: add missing Angular MIT license notices

- projects/core/src/i18n/i18next/i18next-init.spec.ts
- projects/core/src/i18n/i18next/i18next-init.ts
- projects/core/src/i18n/i18next/i18next-providers.ts
- projects/core/src/ssr/ng-express-engine-decorator.ts
- projects/core/src/ssr/ssr.providers.ts
Angular Universal doesn't support using HttpClient with relative URLs, so translations from local JSONs could not be loaded.
Now, only in SSR, the server request host is prepended to the configured path for i18n JSONs.
closes GH-6307
> fix: loading translations from local JSON files when using SSR

- projects/core/src/i18n/i18next/i18next-init.spec.ts
- projects/core/src/i18n/i18next/i18next-init.ts
- projects/core/src/i18n/i18next/i18next-providers.ts
- projects/core/src/ssr/ng-express-engine-decorator.ts
- projects/core/src/ssr/ssr.providers.ts
Angular Universal doesn't support using HttpClient with relative URLs, so translations from local JSONs could not be loaded. See Angular issues:
angular/angular#19224
angular/universal#858
Now, only in SSR, the server request's origin is prepended to the configured path for i18n JSONs.
closes GH-6307
> fix: loading translations from local JSON files when using SSR - for 1.4.x 

- projects/core/src/model/product-search.model.ts
- projects/core/src/occ/adapters/product/converters/occ-product-search-page-normalizer.spec.ts
- projects/core/src/occ/adapters/product/converters/occ-product-search-page-normalizer.ts
- projects/storefrontlib/src/cms-components/product/product-list/product-facet-navigation/product-facet-navigation.component.html
- projects/storefrontlib/src/cms-components/product/product-list/product-facet-navigation/product-facet-navigation.component.ts
The search business tools allow for so-called topValues configuration, a number that indicates the direct visible values of a facet. So far, this number was only hard-coded in Spartacus. With this feature, the business user can customise the number per facet.
The topValues are normalised from the backend to the UI model. A default number (6) is used in case there are no top values given. 
closes #5692
> feat: Support business driven facet top values

- projects/core/src/occ/adapters/product/converters/occ-product-search-page-normalizer.spec.ts
- projects/core/src/occ/adapters/product/converters/occ-product-search-page-normalizer.ts
If a facet contains values that cannot reduce the size of the product result list, it will be removed from the facet list. This is expected from the backend, but as long as this is not implemented, we keep the facet list clean. 
closes #6599
> feat: Remove useless facets from the product result response

- projects/storefrontlib/src/recipes/config/b2c-layout-config.ts
- projects/storefrontstyles/scss/layout/page-templates/_product-list.scss
- projects/storefrontstyles/scss/layout/page-templates/_search-results-list.scss
The various slots on listing pages (category and search) have been ordered with a combination of a layout configuration and order rules in CSS (flexbox) in release 1. This has not been done for a good reason, and it is leading to accessibility issues on the listing page. 
closes #6615 
BREAKING CHANGE:
- the b2cLayoutConfig will change, which will produced a change in the DOM for the category and search pages
- the CSS layout for the category and search pages will no longer use specific "order" for the layout.
> feat: use a clean DOM and CSS for PLP slots
